import type { BlogPost } from "./types"

/** Articles 7–12 (history, etiquette, technical, languages). */
export const blogPostsPart2: BlogPost[] = [
  {
    slug: "fair-play-etiquette-multiplayer-word-games",
    title: "Fair play etiquette in real-time word games",
    date: "2025-03-13",
    description:
      "Respectful norms for screen sharing, spoilers, rematches, and when to concede a stuck round.",
    blocks: [
      { type: "p", text: "WordWave rewards speed, but sustainable communities reward fairness. These norms help public Discords and private friend groups stay welcoming after dozens of matches." },
      { type: "h2", text: "No dictionary sniping" },
      { type: "p", text: "Looking up answers mid-round destroys the social contract. If someone wants a learning mode, agree beforehand and pause the timer—or switch to a trivia tool designed for open research." },
      { type: "h2", text: "Stream delay" },
      { type: "p", text: "Broadcasters should add delay so chat cannot type spoilers into Discord faster than the host sees them. Mention delay length in the title so viewers know." },
      { type: "h2", text: "Disconnects" },
      { type: "p", text: "If a player drops, do not mock them. Offer a rematch code quickly. Life happens—kids, routers, low battery." },
      { type: "h2", text: "Trash talk boundaries" },
      { type: "p", text: "Light teasing about speed is fine for friends who consent. Avoid comments on typing skill tied to disability, language background, or education. When unsure, celebrate good clues instead of mocking misses." },
      { type: "h2", text: "Children in the room" },
      { type: "p", text: "Pick family categories and keep voice chat clean. Hosts can remind players that nicknames are visible to everyone." },
      { type: "h2", text: "When to pause" },
      { type: "p", text: "If someone needs clarification on a bug—not the riddle—pause verbally, fix tech, then restart the round fairly." },
      { type: "h2", text: "Long-term trust" },
      { type: "p", text: "Communities that enforce etiquette attract better opponents. Be the player who models patience; wins feel better anyway." },
      { type: "h2", text: "Recording and clips" },
      { type: "p", text: "Short clips of funny moments help growth, but ask voice participants before uploading audio where local law or platform rules require consent. Blur room codes if you show lobby screens so expired sessions are not harassed." },
      { type: "h2", text: "Mentoring newcomers" },
      { type: "p", text: "Pair rookies with a buddy who explains the mask and timer without rushing. One guided match converts curious visitors into regulars faster than a wall of text." },
    ],
  },
  {
    slug: "timer-rounds-scoring-wordwave",
    title: "Timers, rounds, and scoring in WordWave explained",
    date: "2025-03-15",
    description:
      "What happens when the clock hits zero, how ties are avoided, and how total rounds interact with the win screen.",
    blocks: [
      { type: "p", text: "WordWave’s pacing is simple on the surface: one minute per playing phase, host-selected total rounds, first complete word wins the round. Underneath, edge cases deserve explanation for competitive hosts." },
      { type: "h2", text: "Round clock" },
      { type: "p", text: "The visible timer counts down during play. If nobody completes the word, the round ends with a timeout state and players typically see the solution or partial reveal depending on server configuration for that build." },
      { type: "h2", text: "Simultaneous finishes" },
      { type: "p", text: "The server orders updates; extremely close finishes resolve to a single winner per round. Ties on total score after all rounds may happen; house rule a tiebreaker round or share victory." },
      { type: "h2", text: "Ready between rounds" },
      { type: "p", text: "Skipping ready slows nobody if one player is AFK—communicate in voice chat. The UI blocks progression until everyone confirms, preventing half the group from rushing ahead." },
      { type: "h2", text: "Speech elimination" },
      { type: "p", text: "Bad voice guesses can remove mic privileges for that round while still allowing keyboard input, depending on elimination flags. Read the banner carefully." },
      { type: "h2", text: "Configurable totals" },
      { type: "p", text: "Hosts choose integer round counts. Shorter matches suit lunch breaks; longer ladders suit tournaments. There is no ranked ELO in the base product—track standings externally if you run leagues." },
      { type: "h2", text: "Analytics for improvement" },
      { type: "p", text: "Casually note your average rounds won per night. Trends matter more than single-match spikes." },
      { type: "h2", text: "Host overrides" },
      { type: "p", text: "If your group agrees, the host can verbally pause for bathroom breaks even when the UI still counts down—declare a house pause before anyone starts typing so the round stays honour-based." },
      { type: "h2", text: "Seasonal events" },
      { type: "p", text: "Holiday-themed categories can use the same scoring engine; mention in the lobby that festive clues may reference cultural context outsiders miss, and switch lists if guests feel lost." },
    ],
  },
  {
    slug: "brief-history-word-guessing-games",
    title: "A brief history of word guessing games online",
    date: "2025-03-17",
    description:
      "From hangman classrooms to modern synchronous browsers: why real-time word battles returned in the 2020s.",
    blocks: [
      { type: "p", text: "Word guessing has roots in pencil puzzles and television game shows. Hangman taught spelling; Wheel of Fortune popularised competitive reveals. The web added async play—email hangman, forum riddles—before WebSockets made true simultaneity cheap." },
      { type: "h2", text: "Early multiplayer experiments" },
      { type: "p", text: "Flash-era rooms let users race, but plugins died. Mobile apps filled the gap with isolated silos. Browser games returned as JavaScript matured and hosting became affordable." },
      { type: "h2", text: "Why synchronous matters" },
      { type: "p", text: "Turn-based wordle-likes exploded in popularity, yet party energy often needs everyone staring at the same second on the clock. WordWave targets that niche: lightweight setup, no install." },
      { type: "h2", text: "Educational crossover" },
      { type: "p", text: "Teachers used synchronous typing to drill vocabulary during remote schooling. Similar DNA appears in WordWave’s category system—fun first, learning as side effect." },
      { type: "h2", text: "Future tech" },
      { type: "p", text: "Better on-device speech and cheaper edge databases will keep shrinking latency. The game design problem stays human: fair clues, inclusive language, respectful rooms." },
      { type: "h2", text: "Preservation" },
      { type: "p", text: "Screenshot your high scores; indie games evolve. Blogs like this document intent for players joining years later." },
    ],
  },
  {
    slug: "invite-links-room-codes-safety",
    title: "Invite links, room codes, and basic safety",
    date: "2025-03-19",
    description:
      "What room codes expose, what they do not, and how to share invites in public Discords without drama.",
    blocks: [
      { type: "p", text: "A WordWave room code is a short string pointing at a transient database row. It is not a password to your email, but it is an admission ticket while the room exists." },
      { type: "h2", text: "Public posting risks" },
      { type: "p", text: "If you paste a code in a thousand-person server, strangers may join. Decide if that is desired—great for meetups, chaotic for private couples. Regenerate by creating a fresh room if trolls arrive." },
      { type: "h2", text: "Invite URLs" },
      { type: "p", text: "Links pre-fill join fields but still require a nickname. They do not leak prior player emails. Treat them like codes: share responsibly." },
      { type: "h2", text: "Nickname hygiene" },
      { type: "p", text: "Avoid real full names if you worry about doxxing; pseudonyms are normal. Hosts can ask someone to rename by mutual agreement even though the UI may not force it." },
      { type: "h2", text: "After the game" },
      { type: "p", text: "Rooms eventually clean up server-side. Do not rely on codes as permanent storage of scores—export memories manually." },
      { type: "h2", text: "Kids" },
      { type: "p", text: "Supervise minors sharing links; public lobbies can contain unknown adults." },
    ],
  },
  {
    slug: "mobile-performance-low-latency-tips",
    title: "Mobile browser tips for low-latency WordWave sessions",
    date: "2025-03-21",
    description:
      "Tabs, battery saver, Bluetooth keyboards, and network choices that shave milliseconds off each keystroke.",
    blocks: [
      { type: "p", text: "Phones run WordWave well, but mobile OS multitasking introduces jank. These tweaks help competitive thumb typists." },
      { type: "h2", text: "Close background tabs" },
      { type: "p", text: "Each heavy tab competes for CPU. Safari and Chrome both throttle background timers; a clean window keeps requestAnimationFrame smooth." },
      { type: "h2", text: "Disable ultra power saver" },
      { type: "p", text: "Aggressive battery modes cap JavaScript timers and network polling frequency. Plug in for tournament finals." },
      { type: "h2", text: "External keyboard" },
      { type: "p", text: "Bluetooth keyboards turn phones into mini laptops. Pair before the lobby fills to avoid Bluetooth setup during ready check." },
      { type: "h2", text: "Network selection" },
      { type: "p", text: "5 GHz Wi-Fi or wired tether often beats crowded 2.4 GHz. Run a speed test unrelated to the game; if upload spikes lag, pause cloud backups." },
      { type: "h2", text: "Screen zoom" },
      { type: "p", text: "Ensure browser zoom is 100 percent so the mask aligns with tap targets. System font scaling extremes can misalign custom layouts." },
      { type: "h2", text: "Cooling" },
      { type: "p", text: "Extended sessions heat thin phones; thermal throttling slows input. A desk fan helps more than you expect." },
    ],
  },
  {
    slug: "definition-language-english-romanian-tips",
    title: "Choosing definition language: English, Romanian, and mixed literacy groups",
    date: "2025-03-23",
    description:
      "How hosts should pick clue language when players read at different speeds or bilingual households join.",
    blocks: [
      { type: "p", text: "WordWave separates the language of definitions from the hidden answer’s alphabet quirks via normalisation logic, but humans still read clues in one primary language per round. Picking wisely avoids frustration." },
      { type: "h2", text: "Match the slowest reader" },
      { type: "p", text: "If three players are fluent Romanian and one is learning, run English definitions until they ask for a challenge swap. Mastery beats pride." },
      { type: "h2", text: "Classroom use" },
      { type: "p", text: "Language teachers can run native definitions to force comprehension, then debrief vocabulary after the reveal. Keep rounds low-stakes for beginners." },
      { type: "h2", text: "Mixed households" },
      { type: "p", text: "Families abroad sometimes prefer heritage language definitions to keep kids exposed. Rotate nightly between languages so both parents stay engaged." },
      { type: "h2", text: "Diacritics and keyboards" },
      { type: "p", text: "Answers may include diacritics while typing accepts normalised comparisons—still, remind players how to long-press keys on mobile for special letters if they insist on exact orthography." },
      { type: "h2", text: "Future lists" },
      { type: "p", text: "More languages may appear as categories grow. Track patch notes or this blog when new locales launch." },
      { type: "h2", text: "Accessibility" },
      { type: "p", text: "Screen readers announce definitions; choose concise language settings that your group’s software handles best." },
    ],
  },
  {
    slug: "wordwave-in-classrooms-and-clubs",
    title: "Using WordWave in classrooms and after-school clubs",
    date: "2025-03-25",
    description:
      "Pedagogy notes for teachers: pacing, difficulty, grouping students, and keeping competitive energy positive.",
    blocks: [
      { type: "p", text: "WordWave can reinforce vocabulary when used deliberately. Unlike solitary word searches, the timer adds honest urgency that some students enjoy and others find stressful—balance both groups." },
      { type: "h2", text: "Start cooperative, then competitive" },
      { type: "p", text: "First session: project the definition and solve as a class verbally before anyone types. Second session: pair students on one device so negotiation is part of the learning. Only then run small free-for-all rooms." },
      { type: "h2", text: "Differentiate by category" },
      { type: "p", text: "Advanced learners receive abstract categories; emerging readers stay on concrete nouns with shorter words. Rotate roles so nobody is permanently labelled slow." },
      { type: "h2", text: "Assessment boundaries" },
      { type: "p", text: "Timed games measure speed plus prior knowledge, not deep understanding alone. Use WordWave as formative practice, not high-stakes exams, unless you explicitly teach keyboard fluency as a learning objective." },
      { type: "h2", text: "Noise management" },
      { type: "p", text: "Voice rounds get loud. Establish a hand-raise norm or separate voice sessions to the playground. Headsets reduce bleed between desks in labs." },
      { type: "h2", text: "Privacy" },
      { type: "p", text: "Follow school policy on nicknames; avoid full legal names on screen. Explain that room codes are temporary passes, not gradebook entries." },
      { type: "h2", text: "Debrief template" },
      { type: "p", text: "After three rounds, ask which clue felt fairest and which felt ambiguous. Students learn metalinguistic critique alongside spelling." },
    ],
  },
  {
    slug: "colour-progress-bars-and-accessibility",
    title: "Reading coloured progress lines if you are colour blind",
    date: "2025-03-27",
    description:
      "How WordWave encodes rival progress and what hosts can do to include players who distinguish colours poorly.",
    blocks: [
      { type: "p", text: "WordWave shows each active player with a coloured indicator and a progress representation. Colour is a fast visual channel but not the only one; position in the player list also maps to slots." },
      { type: "h2", text: "Do not rely on hue alone" },
      { type: "p", text: "If you stream, describe lines verbally: “blue player is two letters ahead” rather than “the azure bar”. That habit helps colour-blind viewers and audio-only listeners alike." },
      { type: "h2", text: "Browser zoom" },
      { type: "p", text: "Increasing font size can thicken lines slightly, improving separation. Test at 125 percent zoom before tournaments if a teammate reports confusion." },
      { type: "h2", text: "System filters" },
      { type: "p", text: "macOS and Windows ship colour filters that shift palettes; some players prefer them globally. WordWave cannot override OS settings, but hosts can pause if someone adjusts mid-match." },
      { type: "h2", text: "Future improvements" },
      { type: "p", text: "Patterns or numeric labels beside colours are common accessibility wins; watch release notes if the UI adds them." },
      { type: "h2", text: "Community norm" },
      { type: "p", text: "Ask once per new group whether anyone needs verbal callouts. Normalising the question reduces stigma." },
    ],
  },
]
