import type { StaticBlogPost } from "./types"

/** Articles 1–6 (guides & multiplayer). */
export const blogPostsPart1: StaticBlogPost[] = [
  {
    slug: "how-multiplayer-wordwave-works",
    title: "How multiplayer WordWave works (rooms, codes, and sync)",
    date: "2025-03-01",
    description:
      "A practical walkthrough of creating a room, sharing codes or invite links, ready checks, and what happens when four players compete in real time.",
    blocks: [
      { type: "p", text: "WordWave is built around short, intense rounds. The host starts on the home page, enters a nickname, picks how many players the room allows (two, three, or four), chooses a word category and the language of definitions, and sets how many rounds the match should last. When the room is created, the game generates a four-character code. That code is the address of your session in the database everyone shares." },
      { type: "h2", text: "Joining from a second device" },
      { type: "p", text: "Friends open the same site, switch to “Join”, type the code in uppercase or lowercase—it normalises—and enter their own nicknames. The lobby lists coloured slots so you can see who has taken which seat. Invited players usually fill slots two through four first; the design tries to keep the host in slot one for predictability. If someone disconnects, the room may show a notice; depending on game state the match can continue or end." },
      { type: "h2", text: "Why everyone sees the same definition" },
      { type: "p", text: "Fairness depends on identical information. The server stores one definition and one answer word per round. Each client subscribes to updates for that room row. When the round flips to “playing”, every browser renders the same clue and the same blank pattern. Progress strings for each player are also stored centrally so opponents’ coloured lines stay in sync without trusting one machine as the source of truth." },
      { type: "h2", text: "Ready gates keep starts clean" },
      { type: "p", text: "After players connect, WordWave does not throw you straight into a timed round while someone is still reading the rules. Each participant toggles ready. Only when everyone is marked ready does the next step unlock. The same pattern repeats between rounds: scores update, the word from the finished round may be shown, then players ready up again before the next definition appears. This small friction reduces accidental round starts and gives streamers a moment to address chat." },
      { type: "h2", text: "Invite links versus raw codes" },
      { type: "p", text: "Sharing only four letters is quick in voice chat, but easy to mishear. The lobby can expose a full HTTPS link that opens the home page with the join tab pre-filled. Newcomers still choose a nickname locally; nothing in the link bypasses the name step. That separation keeps personal handles off URLs you paste in public Discords." },
      { type: "h2", text: "Latency and honesty" },
      { type: "p", text: "WordWave is a reflex game: lower network latency helps. Mobile LTE is playable for many users, but crowded Wi-Fi can add tens of milliseconds that matter at the final letter. The client optimistically updates your own mask so typing feels instant, then reconciles with the server. Cheating by inspecting network traffic is possible for motivated engineers; the product targets friends who agree to play fair. For competitive broadcast events, consider honour rules or delayed streams." },
      { type: "h2", text: "What to try next" },
      { type: "p", text: "Run one quiet practice session to learn the timer, then host a two-player duel before inviting a full four-person squad. Rotate hosts so different people experience category selection. If you teach in a classroom, start with English definitions and a broad category, then introduce themed lists once students understand the flow." },
    ],
  },
  {
    slug: "typing-strategies-fast-rounds",
    title: "Typing strategies for fast WordWave rounds",
    date: "2025-03-03",
    description:
      "Finger placement, wrong-letter discipline, and mental models for turning definitions into letters under a one-minute clock.",
    blocks: [
      { type: "p", text: "Sixty seconds sounds generous until you stare at a definition that could map to several lemmas. Strong WordWave players treat each round like a sprint: decode the clue, map phonemes to spelling, and avoid burning time on speculative letters. This article stays keyboard-focused; companion pieces cover voice input and category-specific vocabulary." },
      { type: "h2", text: "Read the definition once, then skim structure" },
      { type: "p", text: "On first read, note part of speech if the clue gives it away—verbs versus nouns change suffix guesses. Count blanks in the mask; length alone eliminates many candidates. If the answer is eight letters and your mind jumps to a six-letter synonym, discard it immediately. Re-reading the same sentence three times rarely beats a single careful pass plus keyboard trial." },
      { type: "h2", text: "Exploit letter frequency, but respect the language" },
      { type: "p", text: "English vowels appear often; Romanian and other languages have their own cadence. If you are unsure between two vowels for an early slot, type the one that appears in the most common stems for that category. WordWave penalises wrong guesses by logging them and shaking the board—two consecutive mistakes can trigger a short lockout—so spamming the alphabet is worse than pausing half a second." },
      { type: "h2", text: "Use opponent lines as soft hints" },
      { type: "p", text: "Coloured progress bars show how far rivals are, not which letters they typed. Still, if two opponents stall on the third position, the definition might hinge on a digraph there. Combine that social signal with your own hypothesis instead of mirroring them blindly." },
      { type: "h2", text: "Hardware and posture" },
      { type: "p", text: "Mechanical keyboards help some players; others prefer low-travel laptop keys. What matters more is consistent posture so you do not miss the home row under stress. On phones, focus mode hides notification banners that cover the input area. Disable auto-correct if it inserts language mismatches when definitions are bilingual." },
      { type: "h2", text: "Cooldown mindset" },
      { type: "p", text: "After a wrong letter, breathe once before the next key. Panic chains cause more errors than careful recovery. The history button lists mistaken characters—review it briefly if you forgot what you already ruled out." },
      { type: "h2", text: "Closing drill" },
      { type: "p", text: "Pick ten practice rounds and log your average time-to-first-letter. Aim to shave a fraction each day by pre-reading categories you find hardest. Speed without accuracy loses rounds; the best curve improves both together." },
    ],
  },
  {
    slug: "voice-input-wordwave-best-practices",
    title: "Using the microphone in WordWave: whole-word tips",
    date: "2025-03-05",
    description:
      "Speech recognition is optional. Learn when it helps, how browsers differ, and why saying the full word beats spelling letter by letter.",
    blocks: [
      { type: "p", text: "WordWave’s microphone path is tuned for whole-word recognition, not dictating individual characters. The speech engine compares transcripts against the hidden answer with tolerance for accents, minor typos, and some fuzzy distance. That design rewards clear enunciation of the solution, not spelling bees into the mic." },
      { type: "h2", text: "Browser support is uneven" },
      { type: "p", text: "Chromium-based desktop browsers generally expose the Web Speech API reliably. Safari and Firefox support varies by version and OS policy. iOS may require tapping the mic in direct response to user gesture; if nothing happens, fall back to typing without treating it as a bug in the game logic." },
      { type: "h2", text: "Environment matters" },
      { type: "p", text: "Background music, room echo, and laptop fans confuse models. A cheap headset dramatically improves accuracy compared to open speakers in a noisy kitchen. Mute television audio temporarily; competitors appreciate it socially as well as acoustically." },
      { type: "h2", text: "Pronunciation versus orthography" },
      { type: "p", text: "If the answer contains a silent letter, speech might still match because the model maps sounds to the stored word. Conversely, homophones can confuse the engine—context from the definition is your tie-breaker. When voice fails twice, switch to keyboard for that round instead of arguing with the browser." },
      { type: "h2", text: "Fair elimination" },
      { type: "p", text: "Multiplayer rounds may mark you as speech-eliminated if your transcript is confidently wrong, preventing hybrid spam where you talk and type conflicting strings. Read the on-screen hint if you lose voice privileges mid-round; it is intentional to keep rounds finite." },
      { type: "h2", text: "Practice pairing" },
      { type: "p", text: "Warm up in solo practice with voice only, then typing only, then both. You learn which mode suits each category. Some themed lists favour long compounds better suited to keyboards; short common nouns often voice well." },
      { type: "h2", text: "Privacy note" },
      { type: "p", text: "Speech processing happens in the browser vendor’s pipeline, not on WordWave servers. Still, avoid saying personal data aloud while the mic is hot. Close the tab after sessions on shared computers." },
    ],
  },
  {
    slug: "practice-mode-before-hosting-friends",
    title: "Why practice mode matters before you host friends",
    date: "2025-03-07",
    description:
      "Solo practice mirrors real rounds without social pressure—ideal for learning categories, timers, and controls.",
    blocks: [
      { type: "p", text: "Hosting a WordWave night means answering questions about timers, scoring, and microphones. If you have never finished a round alone, those questions feel stressful. Practice mode exists to collapse that learning curve into a private session where only you see mistakes." },
      { type: "h2", text: "Same pipeline, zero spectators" },
      { type: "p", text: "Practice draws words from the same category and language configuration you select on the home page. Differences are social: no room codes, no opponent bars, no waiting lobby. That parity matters—you are not training on toy data." },
      { type: "h2", text: "Build muscle memory" },
      { type: "p", text: "Run ten consecutive rounds focusing purely on letter entry rhythm. Then repeat emphasising voice. Track how often you timeout at forty-five seconds—if it is frequent, definitions in that category may be harder for you than expected. Adjust language or theme before inviting others." },
      { type: "h2", text: "Device checklist" },
      { type: "p", text: "Test both portrait and landscape on the phone you will actually use. Confirm brightness auto-dim does not hide the mask mid-round. Plug in headphones if you plan to rely on ambient sound cues later." },
      { type: "h2", text: "Teaching others" },
      { type: "p", text: "After you are comfortable, screen-record one practice round (without showing letters if you plan to share publicly) to send newcomers. A thirty-second clip beats a paragraph of rules." },
      { type: "h2", text: "When to skip practice" },
      { type: "p", text: "Experienced typing-game veterans can jump straight to multiplayer, but even they benefit from one practice session after long breaks or browser updates that might reset permissions." },
      { type: "h2", text: "Rotate categories deliberately" },
      { type: "p", text: "It is tempting to replay only favourite lists. Force one unfamiliar category per session so you are not surprised when a friend picks it live. Variety also keeps the blog screenshots and streams visually fresh." },
    ],
  },
  {
    slug: "word-categories-change-the-game",
    title: "How word categories change difficulty and vibe",
    date: "2025-03-09",
    description:
      "Category choice steers vocabulary breadth, cultural references, and how aggressively you should guess.",
    blocks: [
      { type: "p", text: "WordWave ships multiple themed lists—emotions, body, values, society, and more. Each category biases the distribution of answers. Abstract themes produce longer, rarer lemmas; concrete themes cluster around everyday nouns. Hosts should pick intentionally for the audience, not randomly." },
      { type: "h2", text: "Audience fit" },
      { type: "p", text: "Family rooms with mixed ages benefit from broad, concrete categories where definitions read like dictionary glosses. Niche philosophy lists thrill word nerds but frustrate players who want party energy. Ask the group before locking in." },
      { type: "h2", text: "Language pairing" },
      { type: "p", text: "Definitions can be Romanian while you think in English, or the inverse, depending on host settings. Mixed literacy rooms should align language with the slowest reader, then increase difficulty next match if everyone finishes early." },
      { type: "h2", text: "Metagaming" },
      { type: "p", text: "After several rounds, attentive players internalise category tropes. Rotate hosts or categories to prevent predictability. If you design custom offline lists for classroom use, tag them clearly so imports do not collide with built-ins." },
      { type: "h2", text: "Streaming optics" },
      { type: "p", text: "Colourful category emojis show on screen captures. Pick themes that read well on thumbnail-sized UI. Avoid ultra-narrow topics if chat cannot guess along." },
      { type: "h2", text: "Balanced rotation schedule" },
      { type: "p", text: "A simple format: round one easy category, round two harder, round three wildcard chosen by lowest score. Keeps morale high while still testing skill." },
      { type: "h2", text: "Closing thought" },
      { type: "p", text: "Categories are the closest thing WordWave has to difficulty settings. Treat them as part of matchmaking, not decoration." },
    ],
  },
  {
    slug: "game-night-checklist-wordwave",
    title: "Game night checklist: host WordWave without chaos",
    date: "2025-03-11",
    description:
      "A printable-style checklist for snacks, audio, links, and player onboarding before you press create room.",
    blocks: [
      { type: "p", text: "Spontaneous lobbies are fun, but planned nights run smoother. This checklist targets hosts who want minimal downtime between “everyone arrived” and “first round live”." },
      { type: "h2", text: "Thirty minutes before" },
      { type: "p", text: "Update browsers, charge devices, and open the site once in practice mode to confirm cookies and audio permissions. Write the room code on a sticky note before guests arrive so you are not dictating letters over crunching chips." },
      { type: "h2", text: "Audio and acoustics" },
      { type: "p", text: "If anyone uses voice input, quiet the room or use headsets. For purely typing sessions, background playlist is fine—just keep volume moderate so call-ins on Discord stay intelligible." },
      { type: "h2", text: "Invite flow" },
      { type: "p", text: "Send the HTTPS invite link in your group chat plus the raw code as backup. Mention whether players should join on phone or laptop; mixing is OK but explain landscape recommendation for large thumbs." },
      { type: "h2", text: "House rules" },
      { type: "p", text: "Decide aloud: allowed dictionaries? bathroom breaks between rounds? rematches if disconnect? Clarity prevents mid-game arguments." },
      { type: "h2", text: "During play" },
      { type: "p", text: "Nominate one person to watch the timer voice-over for stream sync. Rotate who reads definitions aloud for players who struggle with small text." },
      { type: "h2", text: "After the match" },
      { type: "p", text: "Screenshot final scores, thank players, and note which category overran time—adjust next week. Archive funny wrong guesses if your community enjoys highlights reels." },
      { type: "h2", text: "Emergency fallback" },
      { type: "p", text: "If the site errors, have a secondary lightweight game ready so the night is not a bust. Rare, but hosts who plan resilience look legendary." },
    ],
  },
]
