const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

// ============================================================
// Comprehensive Romanian word → diacritics dictionary
// ============================================================
const WORD_DICT = {
  // --- Prepositions, conjunctions, particles ---
  'in': 'în', 'si': 'și', 'sa': 'să', 'ca': 'că',
  'fara': 'fără', 'dupa': 'după', 'inca': 'încă',
  'inainte': 'înainte', 'inaintea': 'înaintea',
  'impotriva': 'împotriva', 'impreuna': 'împreună',
  'intrun': 'într-un', 'dintrun': 'dintr-un', 'dintro': 'dintr-o',
  'intrun': 'într-un', 'intro': 'într-o',
  'asupra': 'asupra', 'intr': 'într',
  'pana': 'până', 'panala': 'până la',

  // --- Pronouns ---
  'sine': 'sine', 'sinelui': 'sinelui',
  'tuturor': 'tuturor', 'fiecaruia': 'fiecăruia', 'fiecarui': 'fiecărui',
  'orice': 'orice', 'oricarei': 'oricărei', 'oricarui': 'oricărui',
  'cineva': 'cineva', 'nimeni': 'nimeni', 'nimic': 'nimic',
  'ceilalti': 'ceilalți', 'altii': 'alții', 'altora': 'altora',
  'celuilalt': 'celuilalt', 'celalalt': 'celălalt', 'altuia': 'altuia',
  'altul': 'altul', 'altceva': 'altceva',

  // --- Common verbs ---
  'traieste': 'trăiește', 'traiesti': 'trăiești', 'traim': 'trăim',
  'traire': 'trăire', 'trairea': 'trăirea', 'trait': 'trăit',
  'traind': 'trăind', 'traita': 'trăită', 'traite': 'trăite',
  'traitor': 'trăitor', 'traitori': 'trăitori',
  'creste': 'crește', 'cresterea': 'creșterea', 'cresterii': 'creșterii',
  'crescut': 'crescut',
  'munceste': 'muncește', 'muncesti': 'muncești',
  'gandeste': 'gândește', 'gandesti': 'gândești', 'gandim': 'gândim',
  'gandi': 'gândi', 'gandire': 'gândire', 'gandirii': 'gândirii',
  'gandit': 'gândit', 'gandita': 'gândită', 'ganditor': 'gânditor',
  'gandul': 'gândul', 'gandurile': 'gândurile', 'ganduri': 'gânduri', 'gandurilor': 'gândurilor',
  'simte': 'simte', 'simti': 'simți', 'simtita': 'simțită',
  'simtit': 'simțit', 'simtite': 'simțite', 'simtiri': 'simțiri',
  'simti': 'simți',
  'simturi': 'simțuri',
  'actioneaza': 'acționează', 'actionezi': 'acționezi', 'actiona': 'acționa',
  'ajuta': 'ajuta', 'ajutor': 'ajutor',
  'stie': 'știe', 'sti': 'știi', 'stiind': 'știind',
  'intelege': 'înțelege', 'intelegi': 'înțelegi', 'inteleaga': 'înțeleagă',
  'inteles': 'înțeles', 'inteleasa': 'înțeleasă',
  'intelegere': 'înțelegere', 'intelegerii': 'înțelegerii',
  'incepe': 'începe', 'incepere': 'începere', 'inceput': 'început',
  'inceputul': 'începutul', 'incepand': 'începând',
  'imbunatati': 'îmbunătăți', 'imbunatatirea': 'îmbunătățirea',
  'invata': 'învăța', 'inveti': 'înveți', 'invata': 'învață',
  'invatare': 'învățare', 'invatarea': 'învățarea', 'invatat': 'învățat',
  'invatatii': 'învățații', 'invatatura': 'învățătură',
  'cunoaste': 'cunoaște', 'cunoastere': 'cunoaștere', 'cunoasterea': 'cunoașterea',
  'cunoasterii': 'cunoașterii', 'cunostinte': 'cunoștințe',
  'cunostintelor': 'cunoștințelor', 'cunostiinte': 'cunoștințe',
  'implini': 'împlini', 'implinire': 'împlinire', 'implinit': 'împlinit',
  'implinita': 'împlinită',
  'apara': 'apăra', 'apararea': 'apărarea', 'aparat': 'apărat',
  'imparti': 'împărți', 'impartita': 'împărțită', 'impartite': 'împărțite',
  'impartaseasca': 'împărtășească', 'impartasita': 'împărtășită',
  'impartasite': 'împărtășite', 'impartasita': 'împărtășită',
  'crea': 'crea', 'crearea': 'crearea', 'creat': 'creat',
  'conducere': 'conducere', 'conduca': 'conducă', 'conduce': 'conduce',
  'obtine': 'obține', 'obtii': 'obții', 'obtinerea': 'obținerea',
  'obtinut': 'obținut', 'obtinute': 'obținute',
  'atinge': 'atinge', 'atingi': 'atingi', 'atingerea': 'atingerea', 'atins': 'atins',
  'retragerea': 'retragerea',
  'renunta': 'renunța', 'renuntarea': 'renunțarea',
  'reusi': 'reuși', 'reusita': 'reușită', 'reusitele': 'reușitele',
  'gasi': 'găsi', 'gasire': 'găsire', 'gasirea': 'găsirea',
  'lasa': 'lăsa', 'lasat': 'lăsat',
  'implica': 'implica',
  'submineza': 'subminează',
  'enerva': 'enerva', 'enerveze': 'enerveze',
  'construiesc': 'construiesc',
  'asteapta': 'așteaptă', 'astepta': 'aștepta', 'astepti': 'aștepți',
  'asteptare': 'așteptare', 'asteptarea': 'așteptarea',
  'schimba': 'schimba', 'schimbare': 'schimbare', 'schimbarea': 'schimbarea',
  'schimbul': 'schimbul', 'schimbului': 'schimbului',
  'trata': 'trata', 'tratament': 'tratament',
  'decide': 'decide', 'deveni': 'deveni', 'depasi': 'depăși',
  'depasire': 'depășire',
  'accepta': 'accepta', 'acceptare': 'acceptare', 'acceptarea': 'acceptarea',
  'acceptata': 'acceptată',
  'adapteze': 'adapteze',
  'protejat': 'protejat', 'protejeaza': 'protejează',
  'evita': 'evita', 'evolua': 'evolua',
  'spune': 'spune', 'spuse': 'spuse',
  'aduce': 'aduce', 'aduci': 'aduci',
  'pune': 'pune', 'punerea': 'punerea',
  'citi': 'citi', 'cititul': 'cititul',
  'scrie': 'scrie', 'scris': 'scris', 'scrisul': 'scrisul',
  'defini': 'defini', 'definit': 'definit',
  'imbunatati': 'îmbunătăți',
  'depinde': 'depinde',
  'pierde': 'pierde', 'pierdere': 'pierdere', 'pierderea': 'pierderea', 'pierduta': 'pierdută',
  'privi': 'privi', 'privire': 'privire',
  'vedea': 'vedea', 'vedere': 'vedere',
  'asuma': 'asuma', 'asumare': 'asumare',
  'rezolva': 'rezolva', 'rezolvarea': 'rezolvarea',
  'transmite': 'transmite', 'transmis': 'transmis',
  'refuza': 'refuza',
  'opri': 'opri',
  'urma': 'urma', 'urmas': 'urmaș', 'urmasi': 'urmași',
  'sustine': 'susține', 'sustinere': 'susținere',
  'mentine': 'menține', 'mentinerea': 'menținerea',
  'apartine': 'aparține', 'apartinere': 'apartenență',
  'recunoaste': 'recunoaște', 'recunoasterea': 'recunoașterea',
  'recunosti': 'recunoști', 'recunoscut': 'recunoscut',
  'vrea': 'vrea', 'vrei': 'vrei',
  'adunate': 'adunate',
  'acumulate': 'acumulate',
  'rade': 'râde', 'rasul': 'râsul',
  'invinge': 'învinge', 'invins': 'învins',
  'intreba': 'întreba', 'intrebare': 'întrebare',
  'implica': 'implică',

  // --- Abstract nouns (most common) ---
  'viata': 'viață', 'vietii': 'vieții', 'vietile': 'viețile',
  'viitor': 'viitor', 'viitorului': 'viitorului',
  'sanatate': 'sănătate', 'sanatatea': 'sănătatea', 'sanatatii': 'sănătății',
  'sanatoasa': 'sănătoasă', 'sanatos': 'sănătos',
  'fericire': 'fericire', 'fericirea': 'fericirea', 'fericirii': 'fericirii',
  'tristete': 'tristețe', 'tristetii': 'tristeții',
  'bucurie': 'bucurie', 'bucuria': 'bucuria',
  'furie': 'furie', 'furia': 'furia',
  'frica': 'frică', 'fricii': 'fricii',
  'speranta': 'speranță', 'sperantei': 'speranței',
  'iubire': 'iubire', 'iubirea': 'iubirea',
  'ura': 'ură', 'urii': 'urii',
  'vina': 'vină', 'vinei': 'vinei',
  'rusine': 'rușine', 'rusinea': 'rușinea',
  'mandrie': 'mândrie', 'mandria': 'mândria', 'mandru': 'mândru',
  'mandra': 'mândră',
  'nostalgie': 'nostalgie', 'nostalgia': 'nostalgia',
  'melancolie': 'melancolie', 'melancolia': 'melancolia',
  'anxietate': 'anxietate',
  'panica': 'panică',
  'dezgust': 'dezgust',
  'disperate': 'disperare',
  'disperare': 'disperare', 'disperarea': 'disperarea',
  'suferinta': 'suferință', 'suferintei': 'suferinței',
  'durere': 'durere', 'durerea': 'durerea', 'dureroasa': 'dureroasă',
  'durerosa': 'dureroasă',
  'empatie': 'empatie', 'empatia': 'empatia',
  'compasiune': 'compasiune', 'compasion': 'compasion',
  'gratitudine': 'gratitudine',
  'recunostie': 'recunoștință', 'recunostinta': 'recunoștință',
  'recunostinta': 'recunoștință',
  'tandrete': 'tandrețe', 'tandretea': 'tandrețea',
  'duiosie': 'duioșie', 'duiosia': 'duioșia',
  'blandete': 'blândețe', 'blandetea': 'blândețea',
  'bland': 'blând', 'blanda': 'blândă',
  'maturitate': 'maturitate',
  'incredere': 'încredere', 'increderii': 'încrederii',
  'intelepciune': 'înțelepciune', 'intelepciunii': 'înțelepciunii',
  'libertate': 'libertate', 'libertatea': 'libertatea', 'libertatii': 'libertății',
  'dreptate': 'dreptate', 'dreptatea': 'dreptatea',
  'adevar': 'adevăr', 'adevarul': 'adevărul', 'adevarat': 'adevărat',
  'adevarata': 'adevărată',
  'frumusete': 'frumusețe', 'frumusetea': 'frumusețea',
  'demnitate': 'demnitate',
  'onestitate': 'onestitate', 'onestul': 'onestul', 'onesta': 'onestă',
  'onoarea': 'onoarea',
  'integritate': 'integritate',
  'sinceritate': 'sinceritate', 'sincer': 'sincer', 'sincera': 'sinceră',
  'curaj': 'curaj', 'curajul': 'curajul', 'curajos': 'curajos',
  'rabdare': 'răbdare', 'rabdarea': 'răbdarea', 'rabdator': 'răbdător',
  'tenacitate': 'tenacitate',
  'perseverenta': 'perseverență', 'perseverentei': 'perseverenței',
  'determinare': 'determinare',
  'vointa': 'voință', 'vointei': 'voinței',
  'ambitie': 'ambiție', 'ambitiei': 'ambiției',
  'motivatie': 'motivație', 'motivatia': 'motivația', 'motivatiei': 'motivației',
  'motivatiile': 'motivațiile',
  'scop': 'scop', 'scopul': 'scopul', 'scopurilor': 'scopurilor',
  'succes': 'succes', 'succesul': 'succesul',
  'esec': 'eșec', 'esecul': 'eșecul',
  'greseala': 'greșeală', 'greseli': 'greșeli', 'gresit': 'greșit',
  'putere': 'putere', 'puterea': 'puterea', 'puterii': 'puterii',
  'puternic': 'puternic', 'puternica': 'puternică',
  'energie': 'energie', 'energia': 'energia', 'energiei': 'energiei',
  'spirit': 'spirit', 'spiritul': 'spiritul', 'spiritului': 'spiritului',
  'suflet': 'suflet', 'sufletul': 'sufletul', 'sufletului': 'sufletului',
  'sufleteasca': 'sufletească',
  'inima': 'inimă', 'inimii': 'inimii',
  'minte': 'minte', 'mintea': 'mintea', 'mintii': 'minții',
  'trup': 'trup', 'trupul': 'trupul',
  'corp': 'corp', 'corpului': 'corpului',
  'creier': 'creier', 'creierul': 'creierul',
  'experienta': 'experiență', 'experiente': 'experiențe', 'experientei': 'experienței',
  'cunoastere': 'cunoaștere',
  'inteligenta': 'inteligență', 'inteligentei': 'inteligenței',
  'memorie': 'memorie', 'memoria': 'memoria',
  'imaginatie': 'imaginație', 'imaginatiei': 'imaginației',
  'creativitate': 'creativitate',
  'creativa': 'creativă', 'creativit': 'creativitate',
  'inspiratie': 'inspirație', 'inspiratiei': 'inspirației',
  'inovatie': 'inovație',
  'gandire': 'gândire', 'gandirii': 'gândirii',
  'rationament': 'raționament',
  'ratiune': 'rațiune', 'ratiunii': 'rațiunii',
  'intuitie': 'intuiție', 'intuitiei': 'intuiției',
  'perceptie': 'percepție', 'perceptiei': 'percepției',
  'atentie': 'atenție', 'atentiei': 'atenției', 'atentia': 'atenția',
  'concentrare': 'concentrare',
  'meditatie': 'meditație', 'meditatiei': 'meditației',

  // --- Relationships & society ---
  'familie': 'familie', 'familia': 'familia', 'familiei': 'familiei',
  'prietenie': 'prietenie', 'prietenii': 'prietenii',
  'prieteni': 'prieteni', 'prietenia': 'prietenia',
  'prieten': 'prieten', 'prietenul': 'prietenul', 'prietenului': 'prietenului',
  'prietenilor': 'prietenilor',
  'casatorie': 'căsătorie', 'casatoria': 'căsătoria', 'casatoriei': 'căsătoriei',
  'casatorii': 'căsătorii',
  'casatoria': 'căsătoria',
  'cuplu': 'cuplu',
  'partener': 'partener', 'partenerul': 'partenerul',
  'dragoste': 'dragoste', 'dragostea': 'dragostea',
  'iubire': 'iubire',
  'separare': 'separare', 'divort': 'divorț', 'divortului': 'divorțului',
  'ruptura': 'ruptură',
  'despartire': 'despărțire',
  'desfacerea': 'desfacerea',
  'tradare': 'trădare', 'tradarea': 'trădarea',
  'gelozie': 'gelozie', 'gelozia': 'gelozia',
  'fidelitate': 'fidelitate', 'fidelitatea': 'fidelitatea',
  'fidelitatii': 'fidelității',
  'loialitate': 'loialitate',
  'angajament': 'angajament',
  'devotament': 'devotament',
  'colaborare': 'colaborare',
  'cooperare': 'cooperare',
  'comunicare': 'comunicare',
  'dialog': 'dialog', 'dialogului': 'dialogului',
  'conflictul': 'conflictul', 'conflictului': 'conflictului', 'conflict': 'conflict',
  'violenta': 'violență', 'violentei': 'violenței',
  'agresivitate': 'agresivitate',
  'reconciliere': 'reconciliere',
  'impacare': 'împăcare',
  'iertare': 'iertare', 'iertarea': 'iertarea',
  'comunitate': 'comunitate',
  'societate': 'societate', 'societatii': 'societății',
  'popor': 'popor', 'poporului': 'poporului',
  'natiune': 'națiune', 'natiunii': 'națiunii',
  'cultura': 'cultură',
  'traditie': 'tradiție', 'traditiei': 'tradiției', 'traditii': 'tradiții',
  'obicei': 'obicei', 'obiceiuri': 'obiceiuri',
  'religie': 'religie', 'religioasa': 'religioasă',
  'credinta': 'credință', 'credintei': 'credinței', 'credinte': 'credințe',
  'spiritualitate': 'spiritualitate',
  'rugaciune': 'rugăciune', 'ruganduse': 'rugându-se',
  'biserica': 'biserică', 'bisericii': 'bisericii',
  'dreptate': 'dreptate',
  'justitie': 'justiție',
  'lege': 'lege', 'legea': 'legea',
  'democratie': 'democrație', 'democratia': 'democrația',
  'libertate': 'libertate',
  'egalitate': 'egalitate',
  'discriminare': 'discriminare',
  'rasismul': 'rasismul',
  'coruptia': 'corupția', 'coruptiei': 'corupției',
  'rezistenta': 'rezistență', 'rezistentei': 'rezistenței',
  'revolutie': 'revoluție', 'revolutiei': 'revoluției',
  'reforma': 'reformă',
  'protest': 'protest',
  'revolta': 'revoltă',

  // --- Education & knowledge ---
  'educatie': 'educație', 'educatiei': 'educației',
  'stiinta': 'știință', 'stiintei': 'științei',
  'cunostinte': 'cunoștințe', 'cunostintelor': 'cunoștințelor',
  'matematica': 'matematică',
  'medicina': 'medicină',
  'filozofie': 'filozofie', 'filosofie': 'filosofie',
  'filozofia': 'filozofia', 'filosofia': 'filosofia',
  'logica': 'logică',
  'etica': 'etică',
  'estetica': 'estetică', 'esteticului': 'esteticului',
  'arta': 'artă', 'artele': 'artele',
  'muzica': 'muzică',
  'literatura': 'literatură',
  'carte': 'carte', 'cartea': 'cartea', 'carti': 'cărți',
  'biblioteca': 'bibliotecă', 'bibliotecii': 'bibliotecii',
  'scoala': 'școală', 'scolii': 'școlii',
  'universitate': 'universitate',
  'diploma': 'diplomă',
  'elev': 'elev', 'student': 'student',
  'profesor': 'profesor',
  'mentor': 'mentor', 'mentorat': 'mentorat',
  'studiu': 'studiu', 'studiul': 'studiul',
  'studii': 'studii', 'studiaza': 'studiază',
  'invatamant': 'învățământ',
  'formare': 'formare',
  'predare': 'predare', 'predarii': 'predării',
  'curriculum': 'curriculum',
  'alfabetism': 'alfabetism',
  'pedagogie': 'pedagogie',
  'autodidact': 'autodidact',
  'specializare': 'specializare', 'specializata': 'specializată',
  'expertiza': 'expertiză',
  'competenta': 'competență', 'competentei': 'competenței',
  'abilitate': 'abilitate', 'abilitatea': 'abilitatea',
  'aptitudine': 'aptitudine',
  'talent': 'talent',

  // --- Nature & environment ---
  'natura': 'natură', 'naturii': 'naturii', 'natural': 'natural',
  'naturala': 'naturală',
  'pamant': 'pământ', 'pamantul': 'pământul', 'pamantului': 'pământului',
  'apa': 'apă', 'apei': 'apei',
  'aer': 'aer', 'aerul': 'aerul',
  'foc': 'foc', 'focul': 'focul',
  'soare': 'soare', 'soarele': 'soarele', 'soarelui': 'soarelui',
  'luna': 'lună', 'lunii': 'lunii',
  'stele': 'stele', 'steaua': 'steaua',
  'cer': 'cer', 'cerului': 'cerului',
  'copaci': 'copaci', 'padure': 'pădure', 'padurea': 'pădurea',
  'munte': 'munte', 'munti': 'munți', 'muntii': 'munții',
  'mare': 'mare', 'marea': 'marea',
  'oceane': 'oceane',
  'rauri': 'râuri',
  'campii': 'câmpii',
  'pamant': 'pământ',
  'planta': 'plantă', 'plante': 'plante',
  'frunze': 'frunze',
  'flori': 'flori',
  'animal': 'animal', 'animalele': 'animalele',
  'bacterie': 'bacterie',
  'ciuperca': 'ciupercă',
  'scoartei': 'scoarței',
  'sol': 'sol', 'solul': 'solul',
  'vantul': 'vântul', 'vant': 'vânt',
  'furtuna': 'furtună',
  'ploaia': 'ploaia', 'ploaie': 'ploaie',
  'zapada': 'zăpadă',
  'iarna': 'iarnă',
  'vara': 'vară',
  'toamna': 'toamnă',
  'primavara': 'primăvară',
  'anotimpul': 'anotimpul', 'anotimpuri': 'anotimpuri',
  'temperatura': 'temperatură', 'temperaturii': 'temperaturii',
  'climatul': 'climatul',
  'cutremur': 'cutremur',
  'vulcanul': 'vulcanul',
  'tsunami': 'tsunami',
  'meteorologic': 'meteorologic',
  'precipitatie': 'precipitație', 'precipitatiei': 'precipitației',
  'gravitatie': 'gravitație', 'gravitatiei': 'gravitației',
  'hidratare': 'hidratare',
  'oxigenul': 'oxigenul',
  'clorofila': 'clorofilă',
  'extinctie': 'extincție',
  'reciclare': 'reciclare',
  'refolosirea': 'refolosirea',
  'poluare': 'poluare',
  'incalzire': 'încălzire',
  'ecosistem': 'ecosistem',
  'oceanica': 'oceanică',
  'descompunerea': 'descompunerea',
  'nisip': 'nisip', 'desert': 'deșert',
  'arida': 'aridă',
  'vapori': 'vapori', 'gazos': 'gazos', 'gazul': 'gazul',

  // --- Body & health ---
  'sanatate': 'sănătate',
  'boala': 'boală', 'boli': 'boli', 'bolile': 'bolile',
  'durere': 'durere',
  'vindecare': 'vindecare', 'vindeca': 'vindeca',
  'terapie': 'terapie', 'terapia': 'terapia',
  'terapeutic': 'terapeutic', 'terapeutica': 'terapeutică',
  'chirurgie': 'chirurgie',
  'nutritie': 'nutriție', 'nutritiei': 'nutriției', 'nutritive': 'nutritive',
  'alimentatia': 'alimentația', 'alimentelor': 'alimentelor',
  'dieta': 'dietă',
  'odihna': 'odihnă',
  'somnul': 'somnul', 'somnului': 'somnului',
  'muschilor': 'mușchilor',
  'sangele': 'sângele', 'sange': 'sânge',
  'respiratie': 'respirație', 'respiratiei': 'respirației',
  'respirat': 'respirat', 'respira': 'respira', 'respirul': 'respirul',
  'imunitate': 'imunitate',
  'virusul': 'virusul',
  'contaminarea': 'contaminarea',
  'vitamina': 'vitamină', 'vitamine': 'vitamine',
  'organism': 'organism', 'organul': 'organul',
  'exercitiu': 'exercițiu', 'exercita': 'exercita',
  'sportul': 'sportul',
  'igiena': 'igienă',
  'curatenie': 'curățenie', 'curatenia': 'curățenia',
  'toxice': 'toxice', 'daunatoare': 'dăunătoare',
  'substante': 'substanțe',
  'recuperare': 'recuperare', 'recuperarea': 'recuperarea',
  'tratament': 'tratament',
  'remediu': 'remediu',
  'psiholog': 'psiholog', 'psihologie': 'psihologie',
  'psihologica': 'psihologică', 'psihic': 'psihic', 'psihica': 'psihică',
  'trauma': 'traumă', 'traume': 'traume',
  'depresie': 'depresie',
  'anxietate': 'anxietate',
  'fobia': 'fobia', 'fobie': 'fobie',
  'terapeutica': 'terapeutică',
  'burnout': 'burnout',
  'epuizare': 'epuizare',
  'suprasolicitare': 'suprasolicitare',
  'stresul': 'stresul',
  'relaxare': 'relaxare',
  'yoga': 'yoga',

  // --- Philosophy & religion ---
  'filosoful': 'filosoful', 'filozofia': 'filozofia', 'filozoful': 'filozoful',
  'socrate': 'Socrate', 'platon': 'Platon', 'aristotel': 'Aristotel',
  'descartes': 'Descartes', 'nietzsche': 'Nietzsche',
  'cogito': 'cogito', 'ergo': 'ergo',
  'nihilism': 'nihilism', 'existentialismul': 'existențialismul',
  'stoicism': 'stoicism',
  'epicurism': 'epicurism',
  'pragmatism': 'pragmatism',
  'idealism': 'idealism',
  'relativism': 'relativism',
  'empirism': 'empirism',
  'dialectica': 'dialectică',
  'logica': 'logică',
  'deductia': 'deducția',
  'analogia': 'analogia',
  'dogmatism': 'dogmatism',
  'agnostic': 'agnostic',
  'ateu': 'ateu',
  'dumnezeu': 'Dumnezeu', 'iisus': 'Iisus', 'hristos': 'Hristos',
  'apostol': 'apostol', 'profet': 'profet',
  'sfanta': 'sfântă', 'ceresti': 'cerești', 'divine': 'divine',
  'divin': 'divin', 'divina': 'divină', 'divinitate': 'divinitate',
  'eternitate': 'eternitate', 'vesnice': 'veșnice',
  'iadul': 'iadul', 'paradisul': 'paradisul', 'purgator': 'purgatoriu',
  'reinvierii': 'învierii',
  'rugaciune': 'rugăciune',
  'botez': 'botez',
  'paste': 'Paște', 'craciun': 'Crăciun',
  'sarbatoare': 'sărbătoare', 'sarbatoarea': 'sărbătoarea',
  'coranul': 'Coranul', 'biblia': 'Biblia',
  'crestinism': 'creștinism', 'crestinismului': 'creștinismului',
  'crestin': 'creștin', 'crestinilor': 'creștinilor',
  'islamul': 'islamul',
  'budista': 'budistă',
  'nirvana': 'nirvana',
  'iluminare': 'iluminare',
  'transcendenta': 'transcendență', 'transcendentei': 'transcendenței',
  'reincarnare': 'reîncarnare',
  'karma': 'karma',
  'asezamant': 'așezământ',
  'monah': 'monah', 'monahale': 'monahale',
  'pustnic': 'pustnic',
  'calugareasca': 'călugărească',
  'smerenie': 'smerenie',
  'milostenie': 'milostenie',
  'mila': 'milă',
  'pacat': 'păcat', 'pacate': 'păcate', 'pacatelor': 'păcatelor', 'pacatul': 'păcatul',
  'providenta': 'providență',

  // --- Economy & work ---
  'munca': 'muncă', 'muncii': 'muncii',
  'cariera': 'carieră', 'carierei': 'carierei',
  'job': 'job', 'slujba': 'slujbă',
  'salariu': 'salariu', 'bani': 'bani', 'banilor': 'banilor',
  'avere': 'avere', 'bogatie': 'bogăție', 'bogati': 'bogați',
  'saracie': 'sărăcie', 'saraci': 'săraci',
  'economie': 'economie', 'economia': 'economia', 'economic': 'economic',
  'capitalism': 'capitalism', 'socialism': 'socialism',
  'bugetul': 'bugetul',
  'cheltuieli': 'cheltuieli',
  'castig': 'câștig', 'castigat': 'câștigat', 'castigul': 'câștigul',
  'venit': 'venit',
  'investitie': 'investiție',
  'afacere': 'afacere', 'afaceri': 'afaceri',
  'antreprenoriat': 'antreprenoriat',
  'startup': 'startup',
  'branding': 'branding',
  'marketing': 'marketing',
  'vanzare': 'vânzare',
  'piata': 'piață', 'pietei': 'pieței',
  'concurenta': 'concurență', 'concurentei': 'concurenței',
  'companie': 'companie', 'companiei': 'companiei',
  'profit': 'profit',
  'angajare': 'angajare',
  'concediere': 'concediere',
  'pensie': 'pensie',
  'productie': 'producție', 'productiei': 'producției', 'productiv': 'productiv',
  'munca': 'muncă',
  'voluntar': 'voluntar',
  'firma': 'firmă', 'firme': 'firme',
  'organizatie': 'organizație', 'organizatia': 'organizația', 'organizate': 'organizate',
  'organizata': 'organizată',
  'serviciu': 'serviciu',
  'client': 'client',
  'produs': 'produs', 'produsele': 'produsele',
  'resurse': 'resurse', 'resurselor': 'resurselor',

  // --- Personal development ---
  'autenticitate': 'autenticitate', 'autenticul': 'autenticul', 'autentica': 'autentică',
  'autoestima': 'autoestimare',
  'autoguvernarea': 'autoguvernarea',
  'autonomia': 'autonomia', 'autonomie': 'autonomie',
  'implinire': 'împlinire',
  'realizare': 'realizare',
  'succes': 'succes',
  'performanta': 'performanță', 'performantei': 'performanței',
  'excelenta': 'excelență',
  'progres': 'progres', 'progresul': 'progresul',
  'dezvoltare': 'dezvoltare', 'dezvoltarea': 'dezvoltarea',
  'evolutie': 'evoluție', 'evolutia': 'evoluția', 'evolutii': 'evoluții',
  'crestere': 'creștere',
  'avansare': 'avansare', 'avansarea': 'avansarea', 'avansul': 'avansul',
  'schimbare': 'schimbare',
  'transformare': 'transformare',
  'depasire': 'depășire',
  'obstacol': 'obstacol', 'obstacolelor': 'obstacolelor',
  'provocare': 'provocare', 'provocata': 'provocată',
  'disciplina': 'disciplină',
  'responsabilitate': 'responsabilitate', 'responsabila': 'responsabilă',
  'prioritate': 'prioritate',
  'plan': 'plan', 'planul': 'planul', 'planificarea': 'planificarea',
  'obiectiv': 'obiectiv',
  'tinta': 'țintă',
  'viziune': 'viziune', 'viziunea': 'viziunea',
  'misiune': 'misiune',
  'vocatie': 'vocație', 'vocatia': 'vocația',
  'pasiunea': 'pasiunea', 'pasiv': 'pasiv',
  'activ': 'activ',
  'creativitate': 'creativitate',
  'inovatie': 'inovație',
  'adaptare': 'adaptare',
  'flexibil': 'flexibil',
  'rezilienta': 'reziliență', 'rezilienta': 'reziliență',
  'coping': 'coping',
  'feedback': 'feedback',
  'reflectia': 'reflecția',
  'introspectie': 'introspecție',
  'constiinta': 'conștiință', 'constiintei': 'conștiinței',
  'constient': 'conștient', 'constienta': 'conștienta',
  'discernamant': 'discernământ',
  'intelepciune': 'înțelepciune',
  'balanta': 'balanță',
  'echilibru': 'echilibru',
  'moderatie': 'moderație', 'moderatiei': 'moderației', 'moderate': 'moderate',
  'temperanta': 'temperanță',
  'abstinenta': 'abstinență', 'abstinentei': 'abstinenței',
  'chibzuinta': 'chibzuință',
  'prudenta': 'prudență',
  'precautie': 'precauție',

  // --- Family & life events ---
  'nastere': 'naștere', 'nasterea': 'nașterea', 'nasterii': 'nașterii',
  'nascut': 'născut', 'nascuta': 'născută',
  'copilarie': 'copilărie',
  'copilul': 'copilul', 'copilului': 'copilului', 'copiilor': 'copiilor', 'copil': 'copil',
  'tinerete': 'tinerețe',
  'batranete': 'bătrânețe',
  'moarte': 'moarte', 'moartea': 'moartea',
  'mort': 'mort', 'mostenire': 'moștenire', 'mostenirea': 'moștenirea',
  'urmas': 'urmaș', 'urmasi': 'urmași',
  'mama': 'mamă', 'tata': 'tată', 'tatal': 'tatăl',
  'fiul': 'fiul', 'fiica': 'fiică',
  'frate': 'frate', 'fratele': 'fratele', 'fratelui': 'fratelui',
  'sora': 'soră', 'surorii': 'surorii',
  'bunic': 'bunic', 'bunica': 'bunică',
  'nepot': 'nepot',
  'matusa': 'mătușă',
  'unchi': 'unchi', 'unchiului': 'unchiului',
  'parinte': 'părinte', 'parinti': 'părinți', 'parintelui': 'părintelui',
  'tata': 'tată',
  'aniversare': 'aniversare', 'aniversarea': 'aniversarea',
  'nunta': 'nuntă',
  'divort': 'divorț',
  'adoptie': 'adopție', 'adoptiei': 'adopției',
  'orfan': 'orfan',
  'imigrare': 'imigrare',
  'sot': 'soț', 'sotie': 'soție',
  'baiat': 'băiat',
  'barbatul': 'bărbatul',
  'femeia': 'femeia',
  'varsta': 'vârstă', 'varste': 'vârste',
  'adult': 'adult', 'adultului': 'adultului',

  // --- Values & virtues ---
  'respect': 'respect', 'respecta': 'respecta', 'respectul': 'respectul',
  'respectarea': 'respectarea',
  'onoare': 'onoare', 'onoarea': 'onoarea',
  'demnitate': 'demnitate',
  'integritate': 'integritate',
  'curatenie': 'curățenie',
  'generozitate': 'generozitate', 'generos': 'generos',
  'altruism': 'altruism',
  'daruire': 'dăruire', 'daruieste': 'dăruiește', 'daruirea': 'dăruirea',
  'darul': 'darul',
  'compasiune': 'compasiune',
  'toleranta': 'toleranță', 'tolerantei': 'toleranței',
  'dreptate': 'dreptate',
  'echitate': 'echitate',
  'modestie': 'modestie',
  'smerenie': 'smerenie',
  'umilinta': 'umilință', 'umilintei': 'umilinței',
  'sinceritate': 'sinceritate',
  'transparenta': 'transparență', 'transparent': 'transparent',
  'onestitate': 'onestitate',
  'loialitate': 'loialitate',
  'fidelitate': 'fidelitate',
  'corectitudine': 'corectitudine', 'corect': 'corect', 'corecta': 'corectă',
  'corecte': 'corecte',

  // --- Common adjectives ---
  'bun': 'bun', 'buna': 'bună', 'bune': 'bune', 'bunul': 'bunul',
  'bunstare': 'bunăstare', 'bunastarea': 'bunăstarea',
  'bunatatea': 'bunătatea', 'bunstate': 'bunăstare',
  'rau': 'rău', 'rea': 'rea', 'raul': 'răul', 'raului': 'răului',
  'rele': 'rele',
  'frumos': 'frumos', 'frumoase': 'frumoase', 'frumosul': 'frumosul',
  'greu': 'greu', 'greutatilor': 'greutăților',
  'usor': 'ușor', 'usora': 'ușoară', 'usurinta': 'ușurință', 'usura': 'ușura',
  'rapid': 'rapid', 'repede': 'repede',
  'lent': 'lent', 'lenta': 'lentă',
  'mare': 'mare', 'mic': 'mic', 'mica': 'mică', 'microscopic': 'microscopic',
  'microscopia': 'microscopică', 'microscopica': 'microscopică',
  'vast': 'vast', 'vaste': 'vaste', 'vastitatea': 'vastitatea',
  'adanc': 'adânc', 'adanca': 'adâncă', 'adancul': 'adâncul',
  'inalt': 'înalt', 'inalte': 'înalte',
  'departe': 'departe', 'aproape': 'aproape',
  'cald': 'cald', 'caldura': 'căldură', 'calduros': 'călduros',
  'rece': 'rece',
  'dur': 'dur', 'aspru': 'aspru',
  'dulce': 'dulce',
  'sarata': 'sărată',
  'uscat': 'uscat',
  'umed': 'umed',
  'luminos': 'luminos',
  'nocturn': 'nocturn',
  'vital': 'vital', 'vitale': 'vitale', 'vitalitate': 'vitalitate',
  'mental': 'mental', 'mentala': 'mentală', 'mentale': 'mentale',
  'fizic': 'fizic', 'fizica': 'fizică', 'fizice': 'fizice',
  'fiziologica': 'fiziologică',
  'biologic': 'biologic', 'biologica': 'biologică', 'biologice': 'biologice',
  'genetic': 'genetic',
  'vegetal': 'vegetal',
  'solar': 'solar',
  'electric': 'electric', 'electrica': 'electrică',
  'digital': 'digital', 'digitala': 'digitală',
  'online': 'online',
  'global': 'global', 'globale': 'globale',
  'local': 'local', 'locala': 'locală',
  'modern': 'modern', 'modernism': 'modernism',
  'veche': 'veche',
  'nou': 'nou', 'noua': 'nouă', 'noului': 'noului',
  'ultim': 'ultim', 'ultima': 'ultimă',
  'constant': 'constant', 'constanta': 'constantă',
  'temporar': 'temporar', 'temporara': 'temporară',
  'absolut': 'absolut', 'absoluta': 'absolută',
  'relativ': 'relativ',
  'pozitiv': 'pozitiv', 'pozitia': 'poziția',
  'negativ': 'negativ', 'negativa': 'negativă',
  'activ': 'activ', 'pasiv': 'pasiv',
  'extrovert': 'extrovert', 'extravert': 'extravert',
  'introvert': 'introvert',
  'rigid': 'rigid',
  'suplu': 'suplu',
  'solid': 'solid', 'solida': 'solidă',
  'fluid': 'fluid',
  'plat': 'plat',
  'rotund': 'rotund',
  'colotat': 'colorat', 'colorate': 'colorate', 'multicolor': 'multicolor',
  'colorate': 'colorate',
  'alba': 'albă',
  'moral': 'moral', 'morala': 'morală', 'morale': 'morale',
  'imoral': 'imoral',
  'logic': 'logic', 'rational': 'rațional', 'rationala': 'rațională',
  'emotional': 'emoțional', 'emotionala': 'emoțională', 'emotionale': 'emoționale',
  'sensitiv': 'sensitiv', 'sensibil': 'sensibil', 'sensibilitate': 'sensibilitate',
  'profund': 'profund', 'profunda': 'profundă', 'profunde': 'profunde',
  'superficial': 'superficial',
  'complex': 'complex', 'complicat': 'complicat',
  'simplu': 'simplu', 'simplitate': 'simplitate', 'simplificata': 'simplificată',
  'necesar': 'necesar', 'necesara': 'necesară', 'necesare': 'necesare',
  'important': 'important', 'importanta': 'importanță',
  'esential': 'esențial', 'esentiala': 'esențială', 'esentiale': 'esențiale',
  'fundamental': 'fundamental', 'fundamentala': 'fundamentală', 'fundamentale': 'fundamentale',
  'principal': 'principal', 'principala': 'principală',
  'central': 'central',
  'original': 'original',
  'specific': 'specific', 'specifica': 'specifică',
  'obiectiv': 'obiectiv',
  'subiectiv': 'subiectiv',
  'concret': 'concret', 'concreta': 'concretă',
  'abstract': 'abstract', 'abstracta': 'abstractă', 'abstractie': 'abstracție',
  'defapt': 'de fapt', 'posibil': 'posibil',
  'imposibil': 'imposibil',
  'incapabil': 'incapabil',
  'capabil': 'capabil', 'capacitatea': 'capacitatea',
  'disponibil': 'disponibil', 'disponibila': 'disponibilă',
  'eficient': 'eficient', 'eficace': 'eficace',
  'productiv': 'productiv',
  'creativ': 'creativ', 'creativa': 'creativă',
  'inovator': 'inovator',
  'stiintific': 'științific',
  'academic': 'academic',
  'practic': 'practic', 'practica': 'practică',
  'teoretic': 'teoretic', 'teoria': 'teoria', 'teoriei': 'teoriei',
  'sistematic': 'sistematic', 'sistematica': 'sistematică',
  'ordonat': 'ordonat', 'organizat': 'organizat',
  'haotic': 'haotic', 'haos': 'haos',
  'stabil': 'stabil', 'stabila': 'stabilă', 'stabilitate': 'stabilitate',
  'instabil': 'instabil',
  'echilibrat': 'echilibrat',
  'calm': 'calm', 'calmare': 'calmare',
  'linistit': 'liniștit', 'liniste': 'liniște', 'neliniste': 'neliniște',
  'serenitate': 'serenitate',
  'tensiune': 'tensiune', 'tensiunii': 'tensiunii',
  'stress': 'stres',
  'impulsiv': 'impulsiv',
  'reflexiv': 'reflexiv', 'reflectiv': 'reflectiv',
  'contemplativ': 'contemplativ', 'contemplativa': 'contemplativă',
  'tacit': 'tacit', 'tacita': 'tacită',
  'violent': 'violent',
  'bland': 'blând', 'pacifist': 'pacifist', 'neagresiv': 'neagresiv',
  'avar': 'avar',
  'darnic': 'darnic',
  'arogant': 'arogant',
  'umil': 'umil',
  'trufas': 'trufaș',
  'chibzuit': 'chibzuit',
  'precis': 'precis', 'precisa': 'precisă',
  'vag': 'vag', 'ambiguu': 'ambiguu', 'ambigua': 'ambiguă',
  'clar': 'clar', 'clara': 'clară', 'claritate': 'claritate',
  'neclar': 'neclar',
  'cert': 'cert', 'certitudine': 'certitudine', 'certitudinii': 'certitudinii',
  'incert': 'incert',
  'vulnerabil': 'vulnerabil', 'vulnerabile': 'vulnerabile',
  'rezistent': 'rezistent',
  'puternic': 'puternic',
  'slab': 'slab', 'slabe': 'slabe',
  'obosit': 'obosit', 'oboseala': 'oboseală',
  'sanatos': 'sănătos', 'sanatoasa': 'sănătoasă',
  'bolnav': 'bolnav',
  'tanar': 'tânăr', 'tanara': 'tânără',
  'batran': 'bătrân', 'batrana': 'bătrână',
  'vechi': 'vechi',
  'nou': 'nou',
  'strain': 'străin',
  'nativ': 'nativ',
  'liber': 'liber',
  'constrans': 'constrâns', 'constrangere': 'constrângere',
  'constrangerile': 'constrângerile',
  'prizonier': 'prizonier',
  'independent': 'independent', 'dependnet': 'dependent',
  'interdependent': 'interdependent',
  'egal': 'egal', 'egale': 'egale', 'egalitate': 'egalitate',
  'inegal': 'inegal', 'nedreptate': 'nedreptate',
  'drept': 'drept', 'drepturi': 'drepturi', 'dreptul': 'dreptul', 'dreptii': 'dreptii',
  'obligat': 'obligat', 'obligatia': 'obligația', 'obligatorie': 'obligatorie',
  'datoria': 'datoria', 'datorii': 'datorii',
  'liber': 'liber', 'liberare': 'liberare', 'eliberare': 'eliberare',
  'eliberarea': 'eliberarea',
  'emancipare': 'emancipare',

  // --- Common nouns (misc) ---
  'timp': 'timp', 'timpului': 'timpului', 'zile': 'zile', 'ziua': 'ziua',
  'zi': 'zi', 'zilnica': 'zilnică', 'zilnice': 'zilnice',
  'an': 'an', 'ani': 'ani', 'anului': 'anului',
  'deceniu': 'deceniu', 'secol': 'secol', 'epoca': 'epocă', 'epocii': 'epocii',
  'secunda': 'secundă', 'minut': 'minut', 'minute': 'minute', 'ora': 'oră',
  'moment': 'moment', 'momentul': 'momentul',
  'clipa': 'clipă',
  'trecut': 'trecut', 'trecutului': 'trecutului',
  'prezent': 'prezent', 'prezenta': 'prezență', 'prezentei': 'prezenței',
  'viitor': 'viitor',
  'ciclu': 'ciclu', 'ciclul': 'ciclul',
  'etapa': 'etapă', 'etape': 'etape',
  'perioada': 'perioadă', 'perioade': 'perioade', 'perioda': 'perioadă',
  'trecere': 'trecere', 'trecerea': 'trecerea',
  'tranzitie': 'tranziție', 'tranzitiei': 'tranziției',
  'debutul': 'debutul', 'debut': 'debut',
  'sfarsit': 'sfârșit', 'sfarsitul': 'sfârșitul',
  'final': 'final', 'finala': 'finală', 'finalul': 'finalul',
  'inceput': 'început',
  'incheiere': 'încheiere',
  'terminarea': 'terminarea',
  'finalizare': 'finalizare',
  'absolvire': 'absolvire', 'absolvirea': 'absolvirea',
  'loc': 'loc', 'locul': 'locul',
  'spatiu': 'spațiu',
  'casa': 'casă', 'acasa': 'acasă',
  'cladirea': 'clădirea',
  'zona': 'zonă',
  'suprafata': 'suprafață',
  'teren': 'teren',
  'planeta': 'planetă',
  'galaxia': 'galaxia', 'galaxiei': 'galaxiei',
  'universul': 'universul', 'universului': 'universului',
  'cosmos': 'cosmos',
  'spatiu': 'spațiu',
  'fundatie': 'fundație',
  'structura': 'structură',
  'forma': 'formă', 'forme': 'forme', 'formelor': 'formelor', 'formate': 'formate',
  'formata': 'formată',
  'substanta': 'substanță', 'substante': 'substanțe',
  'material': 'material', 'materiale': 'materiale', 'materialelor': 'materialelor',
  'materie': 'materie', 'materiel': 'material',
  'energie': 'energie',
  'forta': 'forță', 'fortele': 'forțele',
  'miscare': 'mișcare', 'miscarea': 'mișcarea', 'miscari': 'mișcări',
  'ritm': 'ritm',
  'sunet': 'sunet', 'sunetelor': 'sunetelor',
  'lumina': 'lumină',
  'culoare': 'culoare',
  'imagine': 'imagine', 'imagini': 'imagini', 'imaginii': 'imaginii',
  'simbol': 'simbol', 'simbolul': 'simbolul',
  'semn': 'semn',
  'mesaj': 'mesaj', 'mesaje': 'mesaje', 'mesajul': 'mesajul',
  'text': 'text', 'textului': 'textului',
  'document': 'document', 'dosarul': 'dosarul',
  'date': 'date', 'date': 'date',
  'informatie': 'informație',
  'retea': 'rețea',
  'sistem': 'sistem', 'sistemul': 'sistemul', 'sistemului': 'sistemului',
  'sistematica': 'sistematică',
  'metoda': 'metodă', 'metodele': 'metodele',
  'tehnica': 'tehnică', 'tehnicile': 'tehnicile',
  'procedura': 'procedură',
  'regula': 'regulă', 'regulile': 'regulile', 'regulilor': 'regulilor',
  'regulat': 'regulat', 'regulata': 'regulată',
  'norma': 'normă', 'normele': 'normele', 'normelor': 'normelor',
  'principiu': 'principiu', 'principiul': 'principiul', 'principii': 'principii',
  'principiilor': 'principiilor', 'principala': 'principală',
  'lege': 'lege', 'legi': 'legi',
  'contract': 'contract',
  'acord': 'acord', 'acordata': 'acordată',
  'promisiune': 'promisiune',
  'angajament': 'angajament',
  'obligatie': 'obligație',
  'drept': 'drept',
  'responsabilitate': 'responsabilitate',
  'consecinte': 'consecințe', 'consecintele': 'consecințele',
  'cauza': 'cauza', 'cauzei': 'cauzei',
  'efect': 'efect', 'efectul': 'efectul', 'efectului': 'efectului',
  'impact': 'impact',
  'rol': 'rol',
  'functie': 'funcție', 'functiilor': 'funcțiilor', 'functioneaza': 'funcționează',
  'componenta': 'componentă',
  'parte': 'parte', 'parti': 'părți', 'partiala': 'parțială', 'partilor': 'părților',
  'ansamblul': 'ansamblul',
  'suma': 'suma',
  'total': 'total', 'totalitatea': 'totalitatea',
  'intreg': 'întreg', 'intreaga': 'întreagă',
  'diversitate': 'diversitate', 'diferenta': 'diferență', 'diferentele': 'diferențele',
  'diferentelor': 'diferențelor', 'diferite': 'diferite',
  'similitudine': 'similitudine',
  'comparatia': 'comparația',
  'contrast': 'contrast',
  'opozitie': 'opoziție', 'opozitiei': 'opoziției',
  'opus': 'opus', 'opusa': 'opusă', 'opuse': 'opuse', 'opusi': 'opuși',
  'contrariu': 'contrariu', 'contra': 'contra',
  'unitate': 'unitate', 'unificarea': 'unificarea', 'unire': 'unire',
  'separare': 'separare', 'fragmentare': 'fragmentare',
  'conexiune': 'conexiune', 'conexiunea': 'conexiunea',
  'legatura': 'legătură', 'legaturii': 'legăturii',
  'relatie': 'relație', 'relatia': 'relația', 'relatii': 'relații',
  'relatiile': 'relațiile', 'relatiei': 'relației',
  'interactiune': 'interacțiune',
  'comunicare': 'comunicare',
  'schimb': 'schimb',
  'transfer': 'transfer', 'transferul': 'transferul',
  'influenta': 'influență', 'influentei': 'influenței',
  'control': 'control', 'controlul': 'controlul', 'controlului': 'controlului',
  'autoritate': 'autoritate', 'autoritara': 'autoritară',
  'dominatie': 'dominație',
  'putere': 'putere',
  'manipulare': 'manipulare',
  'propaganda': 'propagandă',
  'cenzura': 'cenzură',
  'dictatura': 'dictatură',
  'libertate': 'libertate',
  'dreptul': 'dreptul',
  'justitie': 'justiție',
  'pedepsei': 'pedepsei', 'pedeapsa': 'pedeapsă',
  'sanctiune': 'sancțiune',
  'recompensa': 'recompensă',
  'bonus': 'bonus',
  'premiu': 'premiu',
  'nota': 'notă',
  'evaluare': 'evaluare', 'evaluarea': 'evaluarea',
  'test': 'test', 'examen': 'examen',
  'diploma': 'diplomă',
  'certificat': 'certificat',
  'reclamatie': 'reclamație', 'recomandarea': 'recomandarea',
  'sesizarea': 'sesizarea',
  'plangere': 'plângere',
  'dovada': 'dovadă',
  'argument': 'argument', 'argumentarii': 'argumentării', 'argumentelor': 'argumentelor',
  'demonstratie': 'demonstrație',
  'explicatie': 'explicație',
  'definitie': 'definiție',
  'concept': 'concept',
  'idee': 'idee', 'ideea': 'ideea', 'idei': 'idei', 'ideilor': 'ideilor',
  'teorie': 'teorie', 'teoria': 'teoria', 'teoriei': 'teoriei',
  'ipoteza': 'ipoteză',
  'concluzie': 'concluzie',
  'sinteza': 'sinteză',
  'analiza': 'analiză',
  'cercetare': 'cercetare',
  'studiu': 'studiu',
  'experiment': 'experiment',
  'observatie': 'observație',
  'descoperire': 'descoperire', 'descoperirilor': 'descoperirilor',
  'inventie': 'invenție',
  'revolutie': 'revoluție',
  'inovatie': 'inovație',
  'progres': 'progres',
  'schimbare': 'schimbare',
  'reforma': 'reformă',
  'revolutie': 'revoluție',
  'miscarea': 'mișcarea',
  'campanie': 'campanie',
  'actiune': 'acțiune', 'actiunea': 'acțiunea', 'actiuni': 'acțiuni',
  'actiunii': 'acțiunii', 'actiunilor': 'acțiunilor',
  'reactie': 'reacție',
  'initiativa': 'inițiativă',
  'decizie': 'decizie', 'deciziei': 'deciziei', 'deciziilor': 'deciziilor',
  'alegere': 'alegere', 'alegerea': 'alegerea', 'alegeri': 'alegeri',
  'alegator': 'alegător',
  'votul': 'votul',
  'referendum': 'referendum',
  'partid': 'partid',
  'politic': 'politic', 'politica': 'politică',
  'stat': 'stat', 'statul': 'statul',
  'guvernarii': 'guvernării', 'governa': 'guverna',
  'conducere': 'conducere',
  'lider': 'lider', 'conducator': 'conducător',
  'capitol': 'capitol',
  'program': 'program', 'programare': 'programare',
  'proiect': 'proiect',
  'strategie': 'strategie', 'strategii': 'strategii',
  'tactica': 'tactică',
  'plan': 'plan',
  'obiectiv': 'obiectiv',
  'rezultat': 'rezultat', 'rezultate': 'rezultate', 'rezultatele': 'rezultatele',
  'rezultatelor': 'rezultatelor',
  'performanta': 'performanță',
  'calitate': 'calitate', 'calitatea': 'calitatea',
  'cantitate': 'cantitate',
  'valoare': 'valoare', 'valori': 'valori', 'valorile': 'valorile', 'valorilor': 'valorilor',
  'valoroasa': 'valoroasă',
  'pretios': 'prețios',
  'cost': 'cost', 'plata': 'plată',
  'pret': 'preț',
  'investitie': 'investiție',
  'risc': 'risc', 'riscul': 'riscul',
  'siguranta': 'siguranță',
  'securitate': 'securitate',
  'protectie': 'protecție', 'protectoare': 'protectoare',
  'aparare': 'apărare',
  'granita': 'graniță',
  'limita': 'limită',
  'bariera': 'barieră',
  'obstacol': 'obstacol',
  'blocaj': 'blocaj',
  'impediment': 'impediment', 'impiedica': 'împiedică',
  'dificultate': 'dificultate', 'dificile': 'dificile', 'dificil': 'dificil',
  'dificultatilor': 'dificultăților',
  'provocare': 'provocare',
  'criza': 'criză', 'crizei': 'crizei',
  'urgenta': 'urgență',
  'problema': 'problemă',
  'solutie': 'soluție', 'solutii': 'soluții',
  'raspuns': 'răspuns', 'raspunsuri': 'răspunsuri',
  'intrebare': 'întrebare',
  'dilema': 'dilemă',
  'paradox': 'paradox', 'paradoxul': 'paradoxul',
  'mister': 'mister',
  'necunoscutului': 'necunoscutului',
  'surpriza': 'surpriză',
  'neasteptat': 'neașteptat', 'neasteptata': 'neașteptată',
  'hazard': 'hazard',
  'sansa': 'șansă',
  'noroc': 'noroc',
  'soarta': 'soartă',
  'destin': 'destin',
  'predeterminat': 'predeterminat',
  'providenta': 'providență',
  'miracol': 'miracol',
  'gratie': 'grație',
  'spirit': 'spirit',
  'suflet': 'suflet',

  // --- Verbs/action words ---
  'trece': 'trece', 'trecere': 'trecere',
  'face': 'face', 'faci': 'faci', 'facut': 'făcut', 'facuta': 'făcută', 'faca': 'facă',
  'merge': 'merge', 'deplasa': 'deplasa', 'deplaseaza': 'deplasează',
  'sta': 'sta', 'stai': 'stai',
  'lua': 'lua', 'luat': 'luat',
  'da': 'da',
  'primi': 'primi', 'primit': 'primit', 'primita': 'primită', 'primesti': 'primești',
  'primeasca': 'primească',
  'cumpara': 'cumpăra',
  'vinde': 'vinde',
  'oferi': 'oferi', 'oferit': 'oferit', 'oferita': 'oferită',
  'pierde': 'pierde',
  'gasi': 'găsi',
  'cauta': 'căuta', 'cautarea': 'căutarea',
  'folosi': 'folosi', 'folosirea': 'folosirea', 'folosit': 'folosit', 'folosite': 'folosite',
  'aplica': 'aplica', 'aplicare': 'aplicare', 'aplicarea': 'aplicarea', 'aplicata': 'aplicată',
  'realiza': 'realiza', 'realizare': 'realizare',
  'construi': 'construi', 'construita': 'construită',
  'crea': 'crea',
  'distruge': 'distruge',
  'repara': 'repara',
  'reface': 'reface', 'refacere': 'refacere',
  'innoi': 'înnoi',
  'transforma': 'transforma',
  'schimba': 'schimba',
  'modifica': 'modifica',
  'imbunatati': 'îmbunătăți',
  'optimiza': 'optimiza',
  'maximiza': 'maximiza',
  'minimiza': 'minimiza',
  'reduce': 'reduce', 'reducerea': 'reducerea',
  'elimina': 'elimina', 'excludere': 'excludere', 'excluderea': 'excluderea',
  'includere': 'includere',
  'integra': 'integra',
  'separa': 'separa',
  'combina': 'combina',
  'adauga': 'adăuga',
  'scoate': 'scoate',
  'pune': 'pune',
  'lua': 'lua',
  'aseza': 'așeza', 'asezamant': 'așezământ',
  'organiza': 'organiza',
  'planifica': 'planifica', 'planificarea': 'planificarea',
  'coordona': 'coordona', 'coordonare': 'coordonare',
  'gestiona': 'gestiona',
  'administra': 'administra',
  'conduce': 'conduce',
  'colabora': 'colabora',
  'participa': 'participa',
  'contribui': 'contribui',
  'ajuta': 'ajuta', 'ajutor': 'ajutor',
  'sprijin': 'sprijin',
  'sustine': 'susține',
  'proteja': 'proteja', 'protejat': 'protejat', 'protejeaza': 'protejează',
  'apara': 'apăra',
  'salva': 'salva', 'salvarea': 'salvarea',
  'vindeca': 'vindeca',
  'ingriji': 'îngriji', 'ingrijire': 'îngrijire',
  'hrani': 'hrăni',
  'educa': 'educa',
  'instrui': 'instrui',
  'forma': 'formă', 'formare': 'formare', 'formarea': 'formarea', 'formata': 'formată',
  'indruma': 'îndruma', 'indrumare': 'îndrumare',
  'ghida': 'ghida', 'ghidare': 'ghidare', 'ghideaza': 'ghidează', 'ghidul': 'ghidul',
  'invata': 'învăța',
  'preda': 'preda', 'predare': 'predare',
  'explica': 'explica',
  'demonstra': 'demonstra',
  'proba': 'proba',
  'testa': 'testa',
  'evalua': 'evalua', 'evaluare': 'evaluare',
  'masura': 'măsura', 'masuri': 'măsuri',
  'compara': 'compara', 'comparatia': 'comparația',
  'analiza': 'analiză', 'analizare': 'analizare',
  'observa': 'observa', 'observatie': 'observație',
  'detecta': 'detecta',
  'descoperi': 'descoperi',
  'explora': 'explora', 'explorare': 'explorare',
  'investiga': 'investiga',
  'cerceta': 'cerceta', 'cercetare': 'cercetare',
  'experimenta': 'experimenta',
  'testa': 'testa',
  'dovedi': 'dovedi',
  'confirma': 'confirma',
  'infirma': 'infirma',
  'corecta': 'corectă',
  'critica': 'critica', 'critica': 'critică',
  'judeca': 'judeca',
  'accepta': 'accepta',
  'respinge': 'respinge', 'repulsie': 'repulsie',
  'suporta': 'suporta',
  'tolera': 'tolera', 'toleranta': 'toleranță',
  'ierta': 'ierta', 'iertare': 'iertare',
  'uita': 'uita', 'uitare': 'uitare',
  'aminti': 'aminti', 'amintire': 'amintire', 'amintiri': 'amintiri', 'amintirile': 'amintirile',
  'memorare': 'memorare', 'memoria': 'memoria', 'memorie': 'memorie',
  'comunica': 'comunica', 'comunicare': 'comunicare',
  'exprima': 'exprima', 'exprimare': 'exprimare', 'exprimarea': 'exprimarea',
  'exprimarii': 'exprimării', 'expresia': 'expresia', 'expresie': 'expresie',
  'asculta': 'asculta', 'ascultare': 'ascultare',
  'vorbi': 'vorbi', 'vorbeste': 'vorbește', 'vorba': 'vorbă', 'vorbe': 'vorbe',
  'citi': 'citi',
  'scrie': 'scrie',
  'publica': 'publica',
  'difuza': 'difuză',
  'transmite': 'transmite',
  'receptiona': 'recepționa', 'receptiv': 'receptiv',
  'percepe': 'percepe', 'perceptie': 'percepție',
  'simti': 'simți',
  'vedea': 'vedea',
  'auzi': 'auzi',
  'mirosi': 'mirosi',
  'gusta': 'gusta',
  'atinge': 'atinge',
  'observa': 'observa',
  'nota': 'notă',
  'inregistra': 'înregistra',
  'documenta': 'documenta',
  'stoca': 'stoca', 'stocarea': 'stocarea',
  'procesa': 'procesa',
  'interpreta': 'interpreta',
  'intelege': 'înțelege',
  'cunoaste': 'cunoaște',
  'invata': 'învăța',
  'absorbi': 'absorbi',
  'integra': 'integra',
  'sintetiza': 'sintetiza',
  'genera': 'genera', 'generarea': 'generarea', 'generare': 'generare',
  'produce': 'produce', 'productiei': 'producției',
  'construi': 'construi',
  'elabora': 'elabora',
  'proiecta': 'proiecta', 'proiectia': 'proiecția',
  'concepe': 'concepe',
  'inventa': 'inventa',
  'inova': 'inova',
  'experimenta': 'experimenta',
  'proba': 'proba',
  'implementa': 'implementa',
  'aplica': 'aplica',
  'executa': 'executa', 'executie': 'execuție',
  'realiza': 'realiza',
  'finaliza': 'finaliza', 'finalizare': 'finalizare',
  'completa': 'completa',
  'termina': 'termina', 'terminarea': 'terminarea',
  'incheia': 'încheia',
  'rezolva': 'rezolva',
  'solutiona': 'soluționa',
  'depasi': 'depăși', 'depasire': 'depășire',
  'invinge': 'învinge', 'invins': 'învins',
  'castiga': 'câștiga',
  'pierde': 'pierde',
  'merge': 'merge',
  'avansa': 'avansa', 'avansare': 'avansare', 'avansarea': 'avansarea',
  'retrograda': 'retrograda', 'regres': 'regres', 'stagnare': 'stagnare',
  'stagna': 'stagna',
  'reveni': 'reveni', 'revenirea': 'revenirea', 'revenirii': 'revenirii',
  'reintoarce': 'reintoarce', 'reintalnirea': 'reîntâlnirea',
  'reintegra': 'reintegra', 'reimpacarea': 'reîmpăcarea',
  'recupera': 'recupera',
  'refacere': 'refacere',
  'regenera': 'regenera',
  'reinvia': 'reinvia',
  'reinvierii': 'învierii',
  'rezista': 'rezista', 'rezistenta': 'rezistență',
  'persevera': 'persevera',
  'continua': 'continua', 'continuarea': 'continuarea', 'continuu': 'continuu',
  'persista': 'persista', 'persistenta': 'persistență',
  'insista': 'insista',
  'renunta': 'renunța',
  'abandona': 'abandona',
  'ceda': 'ceda',
  'capitula': 'capitula',
  'accepta': 'accepta',
  'imbraca': 'îmbrăca',
  'imbratisat': 'îmbrățișat',
  'izola': 'izola',
  'conecta': 'conecta',
  'apartine': 'aparține',
  'includ': 'includ',
  'exclude': 'exclude',
  'separa': 'separa',
  'desparte': 'desparte', 'desparti': 'despărți', 'despartire': 'despărțire',
  'unifica': 'unifica',
  'reconcilia': 'reconcilia',
  'media': 'media', 'mediere': 'mediere',
  'negocia': 'negocia', 'negociere': 'negociere',
  'convinge': 'convinge', 'convingere': 'convingere', 'convingeri': 'convingeri',
  'influenta': 'influența',
  'manipula': 'manipula',
  'controla': 'controla',
  'domina': 'domina',
  'subjuga': 'subjuga',
  'elibera': 'elibera',
  'emancipa': 'emancipa',
  'independenta': 'independență',
  'autonomie': 'autonomie',

  // --- Emotions (missing entries) ---
  'emotie': 'emoție', 'emotii': 'emoții', 'emotia': 'emoția', 'emotiei': 'emoției',

  // --- Specific phrases & words from definitions ---
  'simtita': 'simțită', 'adanca': 'adâncă', 'pericolului': 'pericolului',
  'puternica': 'puternică', 'intensa': 'intensă', 'bun': 'bun',
  'asteptarea': 'așteptarea',

  // --- Additional missing words ---
  'fata': 'față', 'fetei': 'feței',
  'intre': 'între', 'intr': 'într',
  'lipsa': 'lipsă', 'lipsei': 'lipsei',
  'jena': 'jenă',
  'teama': 'teamă', 'teamei': 'teamei',
  'ganditoare': 'gânditoare', 'ganditor': 'gânditor',
  'interioara': 'interioară', 'interior': 'interior',
  'admiratie': 'admirație', 'admiratia': 'admirația', 'admiratiei': 'admirației',
  'indoiala': 'îndoială', 'indoielii': 'îndoielii',
  'tendinta': 'tendință', 'tendintei': 'tendinței', 'tendinte': 'tendințe',
  'spirituala': 'spirituală',
  'iubita': 'iubită', 'iubit': 'iubit', 'iubiti': 'iubiți',
  'informatii': 'informații', 'informatia': 'informația', 'informatiei': 'informației',
  'conditia': 'condiția', 'conditie': 'condiție', 'conditii': 'condiții',
  'conditiei': 'condiției', 'conditiile': 'condițiile',
  'lectia': 'lecția', 'lectiei': 'lecției', 'lectii': 'lecții',
  'institutie': 'instituție', 'institutii': 'instituții', 'institutia': 'instituția',
  'conduita': 'conduită', 'conduitei': 'conduitei',
  'realitatii': 'realității',
  'inductia': 'inducția',
  'centrata': 'centrată',
  'luata': 'luată',
  'incitanta': 'incitantă',
  'ocupatia': 'ocupația', 'ocupatiei': 'ocupației',
  'discutie': 'discuție', 'discutii': 'discuții', 'discutiei': 'discuției',
  'interactie': 'interacție', 'interactii': 'interacții', 'interactiei': 'interacției',
  'activitatii': 'activității',
  'bazata': 'bazată',
  'interdependenta': 'interdependență',
  'maretie': 'măreție', 'maretiei': 'măreției',
  'pastrata': 'păstrată',
  'suta': 'sută',
  'cadenta': 'cadență', 'cadentei': 'cadenței',
  'durata': 'durată', 'duratei': 'duratei',
  'rezolutia': 'rezoluția',
  'senzatie': 'senzație', 'senzatii': 'senzații', 'senzatiei': 'senzației',
  'interventie': 'intervenție', 'interventii': 'intervenții',
  'ispita': 'ispită', 'ispitei': 'ispitei',
  'inovatia': 'inovația',
  'difuz': 'difuz',
  'difuza': 'difuză',
  'officiala': 'oficială', 'official': 'oficial',
  'oficiala': 'oficială',
  'insuti': 'însuți', 'insasi': 'însăși',
  'aceiasi': 'aceiași', 'aceeasi': 'aceeași', 'aceasi': 'aceeași',
  'increderea': 'încrederea', 'increderile': 'încrederilesincere',
  'urat': 'urât', 'urata': 'urâtă', 'urati': 'urâți',
  'nascuta': 'născută', 'nascut': 'născut',
  'informatiilor': 'informațiilor', 'informatie': 'informație',
  'persistenta': 'persistentă',
  'perseverenta': 'perseverentă',
  'toleranta': 'tolerantă',
  'abundenta': 'abundentă',
  'importanta': 'importantă',
  'absenta': 'absentă',
  'rezistenta': 'rezistentă',
  'competenta': 'competentă',
  'influenta': 'influență',
  'coerenta': 'coerentă',
  'transparenta': 'transparentă',
  'independenta': 'independentă',
  'evidenta': 'evidentă',
  'diferenta': 'diferentă',
  'constienta': 'conștientă',
  'experienta': 'experientă',
  'existenta': 'existentă',
  'constiinta': 'conștiință', 'constiintei': 'conștiinței',
  'manastire': 'mânăstire',
  'mandrie': 'mândrie', 'mandria': 'mândria',
  'mandriei': 'mândriei', 'mandru': 'mândru', 'mandra': 'mândră',
  'imbratisata': 'îmbrățișată',
  'reziduala': 'reziduală',
  'spiritualitate': 'spiritualitate',
  'saptamana': 'săptămână', 'saptamanilor': 'săptămânilor',
  'tinuta': 'ținută',
  'pastrata': 'păstrată',
  'datina': 'datină', 'datinile': 'datinile',
  'inaintare': 'înaintare',
  'incercarea': 'încercarea', 'incercare': 'încercare',
  'incertitudine': 'incertitudine',
  'inchis': 'închis', 'inchisa': 'închisă',
  'incluziune': 'incluziune',
  'inconstant': 'inconstant',
  'independent': 'independent', 'independenta': 'independență',
  'indignare': 'indignare',
  'indragostiti': 'îndrăgostiți',
  'indrumarea': 'îndrumarea', 'indrumator': 'îndrumător',
  'infectioasa': 'infecțioasă',
  'infiinteaza': 'înființează',
  'ingerul': 'îngerul',
  'inhumare': 'înhumare', 'inhumarii': 'înhumării',
  'inspira': 'inspira',
  'intalnim': 'întâlnim', 'intalnire': 'întâlnire', 'intampla': 'întâmpla',
  'intamplat': 'întâmplat', 'intample': 'întâmple',
  'intarziere': 'întârziere',
  'inteapta': 'înțeaptă',
  'inteleapta': 'înțeleaptă',
  'intelepciunea': 'înțelepciunea',
  'intens': 'intens', 'intensitate': 'intensitate',
  'interes': 'interes', 'interese': 'interese', 'interesului': 'interesului',
  'interiorul': 'interiorul',
  'interval': 'interval',
  'intimitate': 'intimitate',
  'intinderi': 'întinderi',
  'intoarcerea': 'întoarcerea',
  'intotdeauna': 'întotdeauna',
  'intrebarilor': 'întrebărilor',
  'introducerea': 'introducerea',
  'introvert': 'introvert',
  'intuneric': 'întuneric',
  'invatarii': 'învățării',
  'irationala': 'irațională',
  'isi': 'își', 'iti': 'îți',
  'islamului': 'islamului',
  'istoria': 'istoria',
  'iubi': 'iubi', 'iubirii': 'iubirii',
  'izolarea': 'izolarea',
  'jobul': 'jobul', 'jobului': 'jobului',
  'jocul': 'jocul',
  'judeca': 'judeca', 'judecat': 'judecat',
  'jurnalistice': 'jurnalistice',
  'jurul': 'jurul',
  'justitiar': 'justițiar',
  'kant': 'Kant',
  'lacasul': 'lăcașul',
  'lacuri': 'lacuri',
  'leaga': 'leagă',
  'lectura': 'lectură',
  'lichidul': 'lichidul',
  'limit': 'limită', 'limitare': 'limitare', 'limitarea': 'limitarea',
  'limitari': 'limitări', 'limite': 'limite', 'limiteaza': 'limitează',
  'limitele': 'limitele', 'limitelor': 'limitelor',
  'linistire': 'liniștire',
  'lipsit': 'lipsit',
  'locuieste': 'locuiește', 'locuit': 'locuit',
  'loial': 'loial',
  'lucrezi': 'lucrezi', 'lucreaza': 'lucrează',
  'lume': 'lume', 'lumea': 'lumea', 'lumii': 'lumii',
  'lumin': 'lumină', 'luminoase': 'luminoase',
  'lupta': 'luptă',
  'magmatica': 'magmatică',
  'manager': 'manager',
  'manastire': 'mânăstire',
  'manca': 'mânca', 'mancarii': 'mâncării',
  'mandriei': 'mândriei',
  'manie': 'manie',
  'manifesta': 'manifesta', 'manifestarea': 'manifestarea',
  'manipularea': 'manipularea',
  'mantuire': 'mântuire',
  'maretie': 'măreție',
  'marturisirea': 'mărturisirea',
  'masaj': 'masaj',
  'masele': 'masele', 'maselor': 'maselor',
  'masa': 'masă',
  'masurare': 'măsurare',
  'matasii': 'mătăsii',
  'materiala': 'materială',
  'maxim': 'maxim',
  'menire': 'menire',
  'meninerea': 'menținerea',
  'mentale': 'mentale',
  'mereu': 'mereu',
  'metafora': 'metaforă',
  'metoda': 'metodă',
  'micare': 'mișcare', 'micarea': 'mișcarea', 'micari': 'mișcări',
  'minii': 'minții',
  'minciuna': 'minciună',
  'mbuntirea': 'îmbunătățirea',
  'micare': 'mișcare',
  'muschilor': 'mușchilor',
  'nainte': 'înainte', 'naintea': 'înaintea',
  'nalt': 'înalt', 'nalte': 'înalte',
  'naterii': 'nașterii',
  'ncalc': 'încalcă', 'ncepe': 'începe', 'nceput': 'început',
  'nceputul': 'începutul', 'nclcarea': 'încălcarea',
  'ncredere': 'încredere',
  'nelegere': 'înțelegere', 'nelegerii': 'înțelegerii',
  'nelepciune': 'înțelepciune',
  'neateptat': 'neașteptat',
  'neadevrat': 'neadevărat',
  'nereuit': 'nereușită',
  'nestrmutat': 'nestrămutată',
  'nemulumire': 'nemulțumire', 'nemulumiri': 'nemulțumiri',
  'neplcut': 'neplăcută',
  'nva': 'învăța', 'nvare': 'învățare', 'nvei': 'înveți',
  'nvierii': 'învierii',
  'nvmnt': 'învățământ',
  'obii': 'obții', 'obine': 'obține', 'obinerea': 'obținerea',
  'obinut': 'obținut', 'obinute': 'obținute',
  'obligaia': 'obligația',
  'oboseal': 'oboseală',
  'oceanic': 'oceanică',
  'odihn': 'odihnă',
  'pcat': 'păcat', 'pcate': 'păcate', 'pcatelor': 'păcatelor',
  'parial': 'parțial',
  'pastrarea': 'păstrarea',
  'persisten': 'persistență',
  'persoan': 'persoană', 'persoane': 'persoane', 'persoanei': 'persoanei',
  'piat': 'piață', 'pieei': 'pieței',
  'pierdut': 'pierdut',
  'planet': 'planetă',
  'plcere': 'plăcere', 'plcerea': 'plăcerea', 'plcerii': 'plăcerii',
  'plecai': 'plecați',
  'pmnt': 'pământ', 'pmntului': 'pământului',
  'poetic': 'poetică',
  'poi': 'poți',
  'pozitia': 'poziția',
  'precauie': 'precauție',
  'precipitaie': 'precipitație',
  'predrii': 'predării',
  'preios': 'prețios',
  'prere': 'părere', 'prerea': 'părerea',
  'prezenei': 'prezenței',
  'prini': 'părinți', 'printe': 'părinte', 'printelui': 'părintelui',
  'pri': 'părți', 'prilor': 'părților',
  'primeasc': 'primească', 'primeti': 'primești',
  'profunda': 'profundă',
  'produciei': 'producției',
  'profesional': 'profesional', 'profesionala': 'profesională',
  'profesionale': 'profesionale', 'profesionista': 'profesionistă',
  'proiectia': 'proiecția',
  'proportional': 'proporțional',
  'provocata': 'provocată',
  'psihica': 'psihică',
  'psihologica': 'psihologică',
  'puine': 'puține',
  'pur': 'pur', 'pura': 'pură',
  'ran': 'rană', 'rnit': 'rănit',
  'ras': 'rasă',
  'rsrit': 'răsărit',
  'raional': 'rațional', 'raionament': 'raționament', 'raiune': 'rațiune',
  'realitatii': 'realității',
  'rebel': 'rebel',
  'recompens': 'recompensă',
  'rempcarea': 'reîmpăcarea',
  'rentlnirea': 'reîntâlnirea',
  'renuna': 'renunța', 'renunarea': 'renunțarea',
  'repetat': 'repetată',
  'rmas': 'rămas',
  'rnit': 'rănit',
  'salariu': 'salariu',
  'saptamana': 'săptămână',
  'sfnt': 'sfânt', 'sfritul': 'sfârșitul', 'sfrit': 'sfârșit',
  'siguran': 'siguranță',
  'simi': 'simți', 'simit': 'simțit',
  'simplificat': 'simplificată',
  'sincer': 'sincer', 'sincera': 'sinceră',
  'sini': 'sânii',
  'situaie': 'situație', 'situaii': 'situații',
  'slujb': 'slujbă',
  'snge': 'sânge',
  'sntatea': 'sănătatea', 'sntii': 'sănătății', 'sntoas': 'sănătoasă',
  'sor': 'soră',
  'spaiu': 'spațiu',
  'speciala': 'specială', 'specializata': 'specializată',
  'speran': 'speranță',
  'spirituala': 'spirituală',
  'stabila': 'stabilă',
  'stim': 'stimă',
  'strin': 'străin',
  'strnse': 'strânse',
  'structur': 'structură',
  'suplimentara': 'suplimentară',
  'suprafa': 'suprafață',
  'suprem': 'supremă',
  'surs': 'sursă',
  'tact': 'tact',
  'tendinta': 'tendință',
  'tiin': 'știință', 'tiinei': 'științei',
  'tnr': 'tânăr',
  'toi': 'toți',
  'traiului': 'traiului',
  'treptat': 'treptată',
  'triete': 'trăiește', 'trieti': 'trăiești', 'trim': 'trăim',
  'trire': 'trăire', 'trirea': 'trăirea',
  'tristee': 'tristețe', 'tristeii': 'tristeții',
  'trit': 'trăit',
  'uman': 'umană',
  'umilin': 'umilință',
  'uor': 'ușor', 'uurin': 'ușurință',
  'urai': 'urmași',
  'urmeaza': 'urmează',
  'uura': 'ușura',
  'valoroas': 'valoroasă',
  'venice': 'veșnice',
  'via': 'viață',
  'vieii': 'vieții',
  'vin': 'vină',
  'voin': 'voință',
  'vorb': 'vorbă',
  'vrst': 'vârstă',
  'zgomotoas': 'zgomotoasă',
  'zon': 'zonă',

  // --- Answer words (to guess) ---
  'tristete': 'tristețe', 'speranta': 'speranță', 'vinovatie': 'vinovăție',
  'mandrie': 'mândrie', 'rusine': 'rușine', 'invidie': 'invidie',
  'recunostinta': 'recunoștință', 'tanara': 'tânără', 'tandrete': 'tandrețe',
  'gelozie': 'gelozie', 'curiozitate': 'curiozitate',
  'extaz': 'extaz', 'nostalgie': 'nostalgie', 'melancolie': 'melancolie',
  'deznadejde': 'deznădejde', 'entuzasm': 'entuziasm', 'entuziasm': 'entuziasm',
  'rabdare': 'răbdare', 'speranta': 'speranță', 'fericire': 'fericire',
  'bunatate': 'bunătate', 'credinta': 'credință', 'intelepciune': 'înțelepciune',
  'cunoastere': 'cunoaștere', 'educatie': 'educație', 'sanatate': 'sănătate',
  'libertate': 'libertate', 'dreptate': 'dreptate', 'egalitate': 'egalitate',
  'solidaritate': 'solidaritate', 'cooperare': 'cooperare',
  'comunicare': 'comunicare',
  'empatie': 'empatie', 'compasiune': 'compasiune',
  'generozitate': 'generozitate',
  'toleranta': 'toleranță', 'respectul': 'respectul',
  'incredere': 'încredere', 'loialitate': 'loialitate',
  'familie': 'familie', 'prietenie': 'prietenie',
  'casatorie': 'căsătorie', 'iubire': 'iubire', 'dragoste': 'dragoste',
  'separare': 'separare', 'iertare': 'iertare', 'reconciliere': 'reconciliere',
  'nastere': 'naștere', 'copilarie': 'copilărie', 'tinerete': 'tinerețe',
  'maturitate': 'maturitate', 'batranete': 'bătrânețe', 'moarte': 'moarte',
  'mostenire': 'moștenire',
  'natura': 'natură', 'mediu': 'mediu',
  'sustenabilitate': 'sustenabilitate', 'reciclare': 'reciclare',
  'nutritie': 'nutriție', 'exercitiu': 'exercițiu',
  'relaxare': 'relaxare', 'meditatie': 'meditație',
  'creativitate': 'creativitate', 'inovatie': 'inovație',
  'determinare': 'determinare', 'perseverenta': 'perseverență',
  'curaj': 'curaj', 'motivatie': 'motivație', 'succes': 'succes',
  'esec': 'eșec', 'invatare': 'învățare',
  'evolutie': 'evoluție', 'transformare': 'transformare',
  'schimbare': 'schimbare', 'revolutie': 'revoluție',
  'traditie': 'tradiție', 'cultura': 'cultură',
  'identitate': 'identitate', 'diversitate': 'diversitate',
  'egalitate': 'egalitate', 'democratie': 'democrație', 'justitie': 'justiție',
  'drepturile': 'drepturile',
  'etica': 'etică', 'morala': 'morală', 'responsabilitate': 'responsabilitate',
  'integritate': 'integritate', 'onestitate': 'onestitate', 'transparenta': 'transparență',
  'umilinta': 'umilință',
  'terapie': 'terapie', 'vindecare': 'vindecare',
  'optimism': 'optimism', 'pesimism': 'pesimism',
  'mindfulness': 'mindfulness', 'constiinta': 'conștiință',
  'autenticitate': 'autenticitate', 'vulnerabilitate': 'vulnerabilitate',
  'rezilienta': 'reziliență', 'echilibru': 'echilibru',
  'armonie': 'armonie', 'pace': 'pace', 'serenitate': 'serenitate',
  'spiritualitate': 'spiritualitate', 'religie': 'religie',
  'rugaciune': 'rugăciune', 'gratitudine': 'gratitudine',
  'sacrificiu': 'sacrificiu', 'devotament': 'devotament',
  'vocatie': 'vocație', 'menire': 'menire',

  // --- Additional words from Excel ---
  'abis': 'abis', 'abisul': 'abisul',
  'absenta': 'absență', 'absentei': 'absenței',
  'abundenta': 'abundență', 'abundentei': 'abundenței',
  'acceptanta': 'acceptanță',
  'acte': 'acte',
  'actiona': 'acționa',
  'adresata': 'adresată',
  'afla': 'afla', 'aflarea': 'aflarea',
  'afirmatie': 'afirmație',
  'afectiune': 'afecțiune', 'afecta': 'afecta', 'afectat': 'afectat',
  'alianta': 'alianță',
  'alimentar': 'alimentar', 'alocata': 'alocată',
  'amicitie': 'amiciție',
  'ample': 'ample', 'amplu': 'amplu',
  'anumita': 'anumită',
  'aparenta': 'aparență',
  'aparitiei': 'apariției',
  'aportul': 'aportul',
  'apreciere': 'apreciere', 'aprecierea': 'aprecierea',
  'aproximativ': 'aproximativ',
  'aria': 'aria',
  'armat': 'armat',
  'asa': 'așa',
  'ascuns': 'ascuns', 'ascunsa': 'ascunsă',
  'aspectele': 'aspectele',
  'aspiratia': 'aspirația',
  'asociere': 'asociere',
  'atasament': 'atașament',
  'atractia': 'atracția', 'atractie': 'atracție', 'atrage': 'atrage',
  'atragerea': 'atragerea',
  'atribui': 'atribui',
  'aventura': 'aventură',
  'bancuri': 'bancuri', 'braza': 'brațe', 'brate': 'brațe',
  'brusca': 'bruscă',
  'bucati': 'bucăți',
  'calculat': 'calculat',
  'calendaristice': 'calendaristice',
  'cand': 'când',
  'cat': 'cât', 'categoric': 'categoric',
  'catre': 'către',
  'cearta': 'ceartă', 'ceata': 'ceață', 'ceea': 'ceea',
  'celebrarea': 'celebrarea', 'celebrata': 'celebrată',
  'ceva': 'ceva', 'chimia': 'chimia',
  'ciocnire': 'ciocnire', 'circulatiei': 'circulației',
  'clara': 'clară',
  'clasa': 'clasă',
  'clinica': 'clinică',
  'coerent': 'coerent', 'coerenta': 'coerență',
  'coleg': 'coleg',
  'combatere': 'combatere',
  'compatibilitate': 'compatibilitate',
  'complet': 'complet', 'complicatiilor': 'complicațiilor',
  'comportament': 'comportament', 'comportamentul': 'comportamentul',
  'comprehensiunea': 'comprehensiunea',
  'comun': 'comun', 'comune': 'comune',
  'confesiune': 'confesiune',
  'conform': 'conform', 'conformism': 'conformism', 'conformist': 'conformist',
  'confort': 'confort',
  'consecutivi': 'consecutivi', 'consecutive': 'consecutive',
  'consideratie': 'considerație',
  'consiliere': 'consiliere',
  'construirea': 'construirea', 'consumate': 'consumate',
  'contact': 'contact',
  'contemplativa': 'contemplativă',
  'contract': 'contract', 'contrazice': 'contrazice',
  'convingere': 'convingere', 'convingeri': 'convingeri',
  'copaci': 'copaci',
  'corespondenta': 'corespondență', 'corespunde': 'corespunde',
  'corpminte': 'corp-minte',
  'cosmos': 'cosmos',
  'crede': 'crede', 'credincios': 'credincios',
  'creste': 'crește',
  'cuiva': 'cuiva', 'cult': 'cult',
  'cum': 'cum',
  'curcubeu': 'curcubeu', 'curent': 'curent', 'curgatoare': 'curgătoare',
  'curs': 'curs', 'cursuri': 'cursuri',
  'cuvine': 'cuvine',
  'daca': 'dacă',
  'dato': 'dato',
  'dat': 'dat', 'data': 'dată',
  'daunatoare': 'dăunătoare',
  'debut': 'debut', 'decalaj': 'decalaj',
  'decat': 'decât',
  'decodificarea': 'decodificarea',
  'dedicare': 'dedicare',
  'deloc': 'deloc',
  'deosebeste': 'deosebește', 'deosebita': 'deosebită',
  'deplina': 'deplină',
  'depus': 'depus', 'descarcare': 'descărcare',
  'deschide': 'deschide', 'deschidere': 'deschidere', 'deschis': 'deschis',
  'descoperi': 'descoperi',
  'desi': 'deși',
  'destept': 'deștept',
  'detasata': 'detașată',
  'deviere': 'deviere',
  'dialectica': 'dialectică',
  'dimensiunea': 'dimensiunea',
  'dinainte': 'dinainte',
  'directa': 'directă', 'directia': 'direcția',
  'disfunctie': 'disfuncție',
  'disparitia': 'dispariția', 'disparitiei': 'dispariției',
  'dispozitia': 'dispoziția', 'dispozitie': 'dispoziție',
  'distanta': 'distanță', 'distantei': 'distanței',
  'distractie': 'distracție',
  'dobanda': 'dobândă', 'dobandi': 'dobândi', 'dobandire': 'dobândire',
  'dobandirea': 'dobândirea', 'dobandita': 'dobândită', 'dobandite': 'dobândite',
  'doi': 'doi', 'doisprezece': 'doisprezece',
  'domeniu': 'domeniu',
  'dor': 'dor', 'dorinta': 'dorință', 'dorit': 'dorit', 'dorul': 'dorul',
  'doua': 'două',
  'drag': 'drag', 'draga': 'dragă',
  'economie': 'economie', 'educatie': 'educație',
  'electrica': 'electrică',
  'enunt': 'enunț',
  'epuizare': 'epuizare',
  'eronata': 'eronată',
  'esenta': 'esență', 'esential': 'esențial',
  'esentiala': 'esențială', 'esentiale': 'esențiale',
  'evaluare': 'evaluare',
  'exagerata': 'exagerată', 'exagerate': 'exagerate',
  'exces': 'exces', 'excesele': 'excesele',
  'exclusiv': 'exclusiv',
  'existam': 'existăm', 'existent': 'existent', 'exista': 'există',
  'existenta': 'existență', 'existente': 'existente', 'existentei': 'existenței',
  'existi': 'exiști',
  'exterioara': 'exterioară',
  'extrema': 'extremă',
  'faca': 'facă',
  'falsa': 'falsă',
  'farmec': 'farmec',
  'favorabil': 'favorabil',
  'fenomen': 'fenomen',
  'ferm': 'ferm', 'ferma': 'fermă',
  'fidel': 'fidel',
  'fii': 'fii', 'fiinta': 'ființă', 'fiintei': 'ființei',
  'fixa': 'fixă',
  'flirt': 'flirt',
  'foamea': 'foamea',
  'fobia': 'fobia',
  'focusare': 'focusare', 'focusul': 'focusul', 'focus': 'focus',
  'fondator': 'fondator',
  'formarea': 'formarea',
  'fosti': 'foști',
  'frustrare': 'frustrare',
  'fulger': 'fulger',
  'galaxia': 'galaxia',
  'generala': 'generală', 'generatie': 'generație',
  'glume': 'glume', 'glumele': 'glumele',
  'graba': 'grabă',
  'grad': 'grad', 'graduala': 'graduală', 'gradul': 'gradul',
  'grandoare': 'grandoare',
  'grec': 'grec',
  'grija': 'grijă',
  'grup': 'grup', 'grupului': 'grupului', 'grupurilor': 'grupurilor',
  'hotarare': 'hotărâre', 'hotararea': 'hotărârea', 'hotarator': 'hotărâtor',
  'ia': 'ia',
  'ideal': 'ideal', 'ideale': 'ideale',
  'identic': 'identic',
  'ideologie': 'ideologie',
  'ignoranta': 'ignoranță',
  'ii': 'îi',
  'iluzie': 'iluzie',
  'imateriala': 'imaterială',
  'imigrare': 'imigrare',
  'imperativului': 'imperativului',
  'impinge': 'împinge',
  'implicita': 'implicită',
  'impusa': 'impusă', 'impuse': 'impuse',
  'in': 'în',
  'inaltare': 'înălțare',
  'incalca': 'încalcă', 'incalcarea': 'încălcarea',
  'incepe': 'începe',
  'inchise': 'închise',
  'incluziune': 'incluziune',
  'individuale': 'individuale',
  'inegal': 'inegal',
  'infanta': 'înfântă',
  'inregistra': 'înregistra',
  'inseamna': 'înseamnă',
  'instrainare': 'înstrăinare',
  'intersectie': 'intersecție',
  'intim': 'intim', 'intimitate': 'intimitate',
  'intreaga': 'întreagă', 'intreg': 'întreg',
  'intuitiv': 'intuitiv',
  'invaluire': 'înv??luire',
  'invatamant': 'învățământ',
  'invitatie': 'invitație', 'invitat': 'invitat',
  'izolare': 'izolare',
  'jertfire': 'jertfire',
  'judecata': 'judecată',
  'justitie': 'justiție',
  'justificata': 'justificată',
  'laicitate': 'laicitate',
  'lantul': 'lanțul',
  'legatura': 'legătură',
  'legea': 'legea',
  'loial': 'loial',
  'lumina': 'lumină',
  'lupta': 'luptă',
  'macrocosmosul': 'macrocosmosul',
  'magia': 'magia', 'magie': 'magie',
  'mantle': 'mantle',
  'materialism': 'materialism',
  'maxima': 'maximă',
  'membrii': 'membrii', 'membrilor': 'membrilor',
  'metafora': 'metaforă', 'meteo': 'meteo',
  'mijloace': 'mijloace', 'mijloacele': 'mijloacele', 'mijlocul': 'mijlocul',
  'minciuna': 'minciună',
  'mobil': 'mobil',
  'mod': 'mod', 'modelul': 'modelul',
  'mondial': 'mondial', 'monopol': 'monopol',
  'motivul': 'motivul', 'motorul': 'motorul',
  'multime': 'mulțime', 'multimea': 'mulțimea',
  'multumire': 'mulțumire',
  'murdariei': 'murdăriei',
  'mutual': 'mutual',
  'nascuta': 'născută',
  'neadevarat': 'neadevărat',
  'necunoscutului': 'necunoscutului',
  'neindulgent': 'neindulgent',
  'nemultumire': 'nemulțumire', 'nemultumiri': 'nemulțumiri',
  'neplacuta': 'neplăcută',
  'nerabdare': 'nerăbdare', 'nerbdator': 'nerăbdător',
  'nereusita': 'nereușită',
  'nestrumutata': 'nestrămutată',
  'nevoia': 'nevoia', 'nevoie': 'nevoie',
  'nivelul': 'nivelul', 'nivel': 'nivel',
  'noastre': 'noastre',
  'nori': 'nori',
  'nostru': 'nostru',
  'numerelor': 'numerelor', 'numerica': 'numerică',
  'oarba': 'oarbă',
  'obiceiuri': 'obiceiuri',
  'odata': 'odată',
  'ofrandatreaca': 'ofrandă-trecătoare',
  'om': 'om', 'omenirii': 'omenirii', 'omului': 'omului',
  'operelor': 'operelor',
  'oportunitate': 'oportunitate',
  'opunerea': 'opunerea',
  'ordin': 'ordin', 'ordine': 'ordine', 'ordini': 'ordini',
  'orientat': 'orientat',
  'originile': 'originile',
  'ortodoxa': 'ortodoxă',
  'pacat': 'păcat',
  'pace': 'pace', 'pacea': 'pacea',
  'parere': 'părere', 'parerea': 'părerea',
  'parte': 'parte',
  'particular': 'particular',
  'pedagogie': 'pedagogie',
  'permite': 'permite',
  'persoana': 'persoană', 'persoane': 'persoane', 'persoanei': 'persoanei',
  'personale': 'personale',
  'petrecuta': 'petrecută',
  'placere': 'plăcere', 'placerea': 'plăcerea', 'placerii': 'plăcerii',
  'planeta': 'planetă',
  'plecati': 'plecați',
  'plictis': 'plictis',
  'poate': 'poate',
  'poetica': 'poetică',
  'popoare': 'popoare',
  'posibilitate': 'posibilitate', 'posibilul': 'posibilul',
  'post': 'post', 'postul': 'postul',
  'postura': 'postură',
  'poti': 'poți',
  'potrivire': 'potrivire',
  'preconcept': 'preconcept',
  'pregati': 'pregăti', 'pregatire': 'pregătire',
  'presa': 'presa',
  'presiuni': 'presiuni',
  'prestatie': 'prestație',
  'primavara': 'primăvară',
  'primeasca': 'primească', 'primesti': 'primești',
  'primul': 'primul',
  'procesul': 'procesul',
  'produce': 'produce',
  'profesie': 'profesie', 'profesional': 'profesional', 'profesionala': 'profesională',
  'profesionale': 'profesionale', 'profesionista': 'profesionistă',
  'profet': 'profet',
  'proiectia': 'proiecția',
  'promovare': 'promovare', 'promovarea': 'promovarea',
  'proportional': 'proporțional',
  'propria': 'propria', 'proprie': 'proprie', 'proprietatea': 'proprietatea',
  'proprii': 'proprii', 'propriilor': 'propriilor', 'propriu': 'propriu',
  'propus': 'propus',
  'providenta': 'providență',
  'prudenta': 'prudență',
  'publice': 'publice', 'publicului': 'publicului',
  'punctul': 'punctul',
  'pur': 'pur', 'pura': 'pură',
  'purificare': 'purificare',
  'putine': 'puține',
  'radacini': 'rădăcini',
  'radicala': 'radicală',
  'ramas': 'rămas',
  'rana': 'rană', 'ranire': 'rănire', 'ranit': 'rănit',
  'raport': 'raport',
  'rasa': 'rasă',
  'rasarit': 'răsărit',
  'rationala': 'rațională',
  'rebel': 'rebel',
  'recunoaste': 'recunoaște',
  'recompensa': 'recompensă',
  'refolosirea': 'refolosirea',
  'refractar': 'refractar',
  'reglare': 'reglare',
  'regret': 'regret',
  'reimpacarea': 'reîmpăcarea',
  'reintalnirea': 'reîntâlnirea',
  'reinvierii': 'învierii',
  'relativ': 'relativ',
  'relief': 'relief',
  'renuntarea': 'renunțarea',
  'repeta': 'repeta', 'repetata': 'repetată', 'repetitii': 'repetit',
  'reputatie': 'reputație',
  'resentiment': 'resentiment', 'resentimente': 'resentimente',
  'respecta': 'respecta', 'respectarea': 'respectarea',
  'restrictii': 'restricții',
  'retea': 'rețea',
  'retinerea': 'reținerea',
  'reuni': 'reuni', 'reunire': 'reunire',
  'risc': 'risc', 'ritual': 'ritual',
  'rival': 'rival', 'rivalitate': 'rivalitate',
  'rodul': 'rodul',
  'romantic': 'romantic', 'romantism': 'romantism',
  'ruptura': 'ruptură',
  'sacrificiu': 'sacrificiu',
  'saizeci': 'șaizeci',
  'salvarea': 'salvarea',
  'sapte': 'șapte',
  'sarut': 'sărut',
  'satelitul': 'satelitul',
  'satisfactie': 'satisfacție',
  'scepticism': 'scepticism',
  'scoartei': 'scoarței',
  'secretul': 'secretul',
  'secventa': 'secvență',
  'seductia': 'seducția', 'seductiei': 'seducției',
  'selectarea': 'selectarea', 'selectie': 'selecție',
  'semnificatie': 'semnificație',
  'sens': 'sens', 'sensul': 'sensul',
  'setea': 'setea',
  'sezon': 'sezon',
  'sfatul': 'sfatul',
  'sigur': 'sigur',
  'simplu': 'simplu',
  'sincer': 'sincer', 'sincera': 'sinceră',
  'singur': 'singur',
  'situatie': 'situație', 'situatii': 'situații',
  'slujba': 'slujbă',
  'so': 'so',
  'social': 'social', 'sociale': 'sociale',
  'socoteala': 'socoteală',
  'solidar': 'solidar',
  'solutii': 'soluții',
  'sora': 'soră',
  'special': 'special', 'speciala': 'specială', 'specialist': 'specialist',
  'specii': 'specii', 'speciilor': 'speciilor',
  'sprijin': 'sprijin',
  'stabila': 'stabilă',
  'stagnare': 'stagnare',
  'startup': 'startup',
  'stereotip': 'stereotip',
  'stima': 'stimă',
  'stoicism': 'stoicism',
  'stranse': 'strânse',
  'structura': 'structură',
  'subiect': 'subiect',
  'submineza': 'subminează',
  'suficient': 'suficient',
  'sum': 'sum',
  'superior': 'superior',
  'suplimentara': 'suplimentară',
  'suport': 'suport',
  'suprafata': 'suprafață',
  'supraomului': 'supraomului',
  'suprema': 'supremă',
  'supunere': 'supunere',
  'sursa': 'sursă',
  'tact': 'tact',
  'tale': 'tale', 'tau': 'tău',
  'ta': 'ta',
  'te': 'te', 'tie': 'ție',
  'temei': 'temei',
  'termenul': 'termenul', 'termen': 'termen',
  'tine': 'tine',
  'tinta': 'țintă',
  'toamna': 'toamnă',
  'tot': 'tot', 'totala': 'totală', 'totalitatea': 'totalitatea', 'toti': 'toți',
  'totul': 'totul',
  'tradarea': 'trădarea',
  'traim': 'trăim',
  'transmis': 'transmis',
  'traseul': 'traseul',
  'tratat': 'tratat',
  'treaz': 'treaz',
  'trebuie': 'trebuie',
  'treizeci': 'treizeci',
  'treptata': 'treptată',
  'trezire': 'trezire',
  'tunet': 'tunet',
  'uitare': 'uitare',
  'umana': 'umană', 'umanism': 'umanism',
  'umor': 'umor', 'umorul': 'umorul',
  'una': 'una', 'unchi': 'unchi',
  'unica': 'unică', 'unic': 'unic',
  'unii': 'unii', 'unile': 'unele',
  'uniunea': 'uniunea',
  'unor': 'unor', 'unui': 'unui',
  'urgenta': 'urgență',
  'urias': 'uriaș',
  'uzate': 'uzate',
  'va': 'va',
  'val': 'val', 'validarea': 'validarea',
  'vastitatea': 'vastitatea',
  'vecin': 'vecin',
  'veghere': 'veghere',
  'venirea': 'venirea',
  'ver': 'ver',
  'verticalul': 'verticalul',
  'veselie': 'veselie',
  'vie': 'vie', 'viu': 'viu',
  'vigoare': 'vigoare',
  'vizibilitate': 'vizibilitate',
  'vocatia': 'vocația',
  'vocea': 'vocea',
  'vorba': 'vorbă',
  'votul': 'votul',
  'vreme': 'vreme',
  'zi': 'zi', 'zona': 'zonă',
  'zgomot': 'zgomot', 'zgomotoasa': 'zgomotoasă',
  'zece': 'zece',
};

// Apply patterns for "-tie/-tii/-tiei" etc. (common Romanian suffixes)
const SUFFIX_PATTERNS = [
  // These are highly reliable
  [/tion$/, 'tion'], // keep English-style
  [/stiinta$/, 'știință'],
  [/stiintei$/, 'științei'],
];

function fixWord(word) {
  const lower = word.toLowerCase();
  if (WORD_DICT[lower] !== undefined) {
    // Preserve original capitalization
    const fixed = WORD_DICT[lower];
    if (word[0] === word[0].toUpperCase() && fixed[0]) {
      return fixed[0].toUpperCase() + fixed.slice(1);
    }
    return fixed;
  }
  return word;
}

function fixText(text) {
  if (!text) return text;
  // Replace word by word, preserving non-word characters
  return text.replace(/[a-zA-ZăâîșțĂÂÎȘȚ]+/g, (match) => fixWord(match));
}

// Read Excel
const wb = XLSX.readFile('C:/Users/hdavi/Downloads/viata_1000_definitii_jocul_cuvintelor.xlsx');
const ws = wb.Sheets['Toate Definitiile'];
const data = XLSX.utils.sheet_to_json(ws, { header: 1 });
const rows = data.slice(2).filter(r => r[1] && r[3] && r[4]);

const CATEGORY_MAP = {
  'EMOTII': 'emotii',
  'RELATII': 'relatii',
  'SANATATE': 'sanatate',
  'NATURA': 'natura',
  'FILOZOFIE': 'filozofie',
  'EDUCATIE': 'educatie',
  'VIATA': 'viata',
  'FAMILIE': 'familie',
  'VALORI': 'valori',
  'MUNCA': 'munca',
  'SOCIETATE': 'societate',
  'RELIGIE': 'religie',
  'STIINTA': 'stiinta',
  'ECONOMIE': 'economie',
  'PSHIOLOGIE': 'psihologie',
  'PSIHOLOGIE': 'psihologie',
  'SPIRITUALITATE': 'spiritualitate',
  'COMUNICARE': 'comunicare',
  'DEZVOLTARE': 'dezvoltare',
  'TIMP': 'timp',
};

const categories = {};
rows.forEach(r => {
  const cat = r[1].toString().trim().toUpperCase();
  const key = CATEGORY_MAP[cat] || cat.toLowerCase();
  if (!categories[key]) categories[key] = [];

  const rawWord = r[4].toString().trim();
  const rawDef  = r[3].toString().trim();

  const word = fixText(rawWord.toLowerCase());
  const definition = fixText(rawDef);

  categories[key].push({ word, definition });
});

let totalFiles = 0;
for (const [key, entries] of Object.entries(categories)) {
  const outPath = path.join('public', `${key}.json`);
  fs.writeFileSync(outPath, JSON.stringify(entries, null, 2), 'utf8');
  console.log(`Written ${outPath} (${entries.length} entries)`);
  totalFiles++;
}
console.log(`\nDone! ${totalFiles} files written.`);
